### ISSUE TITLE
Add `application_type` to relevant views

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#103]
@fwaumans can you add the field `application_type` to:

- [x] `projects_view2`: rename `context_type`, see #102 
- [x] `receivers_view2`: already the case, as 3rd field (between `receiver_id` and `telemetry_type`)
- [x] `deployments_view2`: field `application_type` as 3rd field (between `receiver_id` and `network_project_code`)
- [x] `detections_view2`: field `application_type` as 4th field (between `receiver_id` and `network_project_code`)

**Comment by fwaumans** [comment]
done!

**Comment by peterdesmet** [comment]
Nice! The change resulted in 3 failed tests as expected: now updated.
