### ISSUE TITLE
Allow filtering on application_type

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#104]
Answers #85 and #79. Can be implemented once #103 is done:

- [x] Add parameter `application_type` to `get_projects()`:
  - [x] Default: `NULL`
- [x] Add parameter `application_type` to `get_receivers()`:
  - [x] Default: `NULL`
- [x] Add parameter `application_type` to `get_deployments()`:
  - [x] Default: `NULL`
- [x] Maybe add parameter `application_type` to `get_detections()`:
  - [x] Default: `NULL`
- [ ] Maybe add function `list_application_types()`: no need

@PieterjanVerhelst @IPauwels @jreubens should `application_type` have a default value `acoustic` or no default value. My preference is the latter: simpler to implement and keeps `cpod` and `acoustic` at same level.

**Comment by PieterjanVerhelst** [comment]
I agree. If the purpose of the ETN-package is to get access to all kinds of tracking data (acoustic, cpod...), there should not be a default value.

**Comment by IPauwels** [comment]
agree as well!

**Comment by peterdesmet** [comment]
@IPauwels @jreubens Ok, what kind of values do you want the user to provide? Currently the values in the database are: `acoustic_telemetry` and `cpod`.

Do you prefer these, or should we shorted them to `acoustic` and `cpod`, keeping in mind that more values could be added in the future and that we should avoid changing these values.

**Comment by peterdesmet** [comment]
Is now implemented with `acoustic_telemetry` and `cpod`. Reopen if you want other values.

**Comment by IPauwels** [comment]
I leave it up to Jan to make a final decision. Personally I would keep acoustic_telemetry. Because CPOD is also based on acoustics, and acoustic_telemetry is more referring to "remotely measuring" (since you tag the animal) so perhaps closer related to the true definition of tele-metry..

**Comment by jreubens** [comment]
currently we can leave it as is.
DB structure will change in the future, and then we'll need to do some adaptations I guess
