### ISSUE TITLE
Hide check_date_time

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#107]
I notice we have a doc page for https://inbo.github.io/etn/reference/check_date_time.html. Shouldn't this be hidden? It has:

https://github.com/inbo/etn/blob/0722c9a17eb33b8de9653543cfb94989169b5920/R/zzz.R#L116

Other functions in `zzz.R` seem to be hidden.

**Comment by damianooldoni** [comment]
Indeed. I'll do it.
