### ISSUE TITLE
Update animals_view2 regarding animal_id

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#109]
As discussed in #74, we would like `animal_id` to be a duplicate of `pk`, as that will be used the primary identifier of the animal.

## Changes in animals_view2

- [x] rename the current user-edited field `animal_id` to `animal_label` (ideally also in interface)
- [x] place `animal_label` between `aphia_id` and `animal_nickname`
- [x] add a field `animal_id` with the same content as `pk` (in place 2)

pk | animal_id | animal_project_code | tag_id | tag_fk | scientific_name | common_name | aphia_id | animal_label | animal_nickname
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
234 | 234 | 2011_rivierprik | A69-1303-3556 | 213 | Lampetra fluviatilis | river lamprey | | | 
235 | 235 | 2015_phd_verhelst | A69-1601-13631 | 405 | Gadus morhua | Atlantic cod | | A1 | 

## Changes in detections_view2

- [x] The content of `animal_id` should be that of the new `animal_id` (= `animal_fk`)

**Comment by peterdesmet** [comment]
@PieterjanVerhelst @IPauwels @jreubens can you review the above, so @fwaumans can implement this?

**Comment by PieterjanVerhelst** [comment]
I agree

**Comment by jreubens** [comment]
I agree as well

**Comment by peterdesmet** [comment]
Great, @fwaumans you can then implement these changes in the two views mentioned above (when telework/time allows). Ping me here if done, so I can update the function.

**Comment by IPauwels** [comment]
Agree as well :-)

**Comment by fwaumans** [comment]
@peterdesmet : I will do this during this week, asap.

**Comment by fwaumans** [comment]
@peterdesmet : Can you check?

**Comment by peterdesmet** [comment]
Looks good in `animals_view2`, but in `detections_view2` the field `animal_id` seems to be `NA` while it should have the same content as `animal_fk`. Since this is now a duplicate field, the action to take can be:

- [ ] In `detections_view2`, replace `animal_fk` with `animal_id` (same content)

**Comment by fwaumans** [comment]
@peterdesmet : Can you check agian?

**Comment by peterdesmet** [comment]
Almost 😁  `animal_label` can be removed from detections, so:

> pk, date_time, receiver_id, application_type, network_project_code, tag_id, tag_fk, animal_id, animal_project_code, scientific_name, ...

**Comment by fwaumans** [comment]
@peterdesmet : new attempt

**Comment by peterdesmet** [comment]
Great! Now ok.
