### ISSUE TITLE
Public website with fields and definitions for all views

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#113]
@fwaumans @jreubens (and @PieterjanVerhelst @IPauwels) at the January meeting, we mentioned setting up a **public website with the fields and definitions of the 6 main ETN views** (i.e. what is in the ETN fields & definitions spreadsheet). The website would ideally:

- Be referenced by published datasets, so external users of the data can read the definitions of the fields they want to use and publishers don't have to repeat that information for each dataset. Therefore: website needs stable URL **this feature is the most urgent**
- Have term links/anchors, so one can reference the definition of a specific field, c.f. Darwin Core term URLs in `meta.xml`: http://rs.tdwg.org/dwc/terms/scientificName
- Allow community suggestions, e.g. by hosting it on GitHub, which could even directly update the application as well.
- Be versioned, so datasets can specify which version of the schema they use.

Good examples are e.g. the Movebank Attribute Directory (https://www.movebank.org/cms/movebank-content/movebank-attribute-dictionary) which is fully versioned on http://vocab.nerc.ac.uk/collection/MVB (a service ETN could use as well).

I understand that all of this might be too much to tackle at once, but even a GitHub repository with the definitions in one Markdown page would go a long way as reference. Alternatively, we could make it a page in the documentation of this package, but I feel it would be better to be kept separate?

Let me hear your thoughts, as we'll need something soon for the datasets we will publish. What is feasible on the short term? And who do you want to tackle this?

**Comment by jreubens** [comment]
@fwaumans what is your opinion on this? I've never done this before...

**Comment by fwaumans** [comment]
@peterdesmet @jreubens We could provide a repository on github.com/lifewatch  for this goal. How will we feed this page?

**Comment by peterdesmet** [comment]
Well, how you feed it depends on where you want to keep the source fieldnames and their definitions.

## If those are maintained in the database

- Suggestions made here on the website (like fixing typos), will then manually need to be copied to the database by someone from VLIZ
- You will need an automated way to export the info from the database, and code it in a way that can be displayed nicely here (e.g. yaml parsed to html)

## If those are maintained in this repository

- People will be able to make suggestions, as the source files (should be machine and human-readable, like yaml) are kept in the repository
- You will need an automated way to export the information in this repo to the database and more importantly application

**Comment by fwaumans** [comment]
I think the best option is to maintain this in the database because most of the definitions are already stored in the database.

**Comment by peterdesmet** [comment]
Can you easily export these as yaml? See https://inbo.github.io/ctms/terms/ for an example on how we can display the information from yaml

**Comment by fwaumans** [comment]
The information is stored in a table of the database. I have to convert it to a yaml. I will do this in the last week of april.

**Comment by peterdesmet** [comment]
Great! Obviously best if this output to yaml can be generated automatically/repeatably, so changes only need to be manually in one place (the database).

**Comment by fwaumans** [comment]
I have exported the fields and their definitions in a JSON file. Is this ok for you?
[metadata.txt](https://github.com/inbo/etn/files/5186768/metadata.txt)

**Comment by peterdesmet** [comment]
I can probably work with that.

@jreubens should this be displayed to the user on the ETN R package website (that is something I can take care of) or did you have another place in mind?

**Comment by jreubens** [comment]
@peterdesmet ETN R package website seems good place to me

**Comment by peterdesmet** [comment]
@fwaumans I inspected the JSON file. Would it be possible to:

1. Indicate which **view** a field belongs to
2. Have the fields in the order they appear in
3. Indicate the field type

Thanks!

**Comment by peterdesmet** [comment]
Based on the json file, I have now created an extra page (not online yet):

<img width="871" alt="Screenshot 2020-09-11 at 09 56 40" src="https://user-images.githubusercontent.com/600993/92887979-33df8a80-f415-11ea-97ca-a320d0d0141b.png">

But as mentioned, it would be better if these fields were organized by view + have data type. @jreubens Thoughts?

**Comment by peterdesmet** [comment]
Page is online, so you can see: https://inbo.github.io/etn/articles/etn_fields.html

**Comment by PieterjanVerhelst** [comment]
Great 👍 !

**Comment by jreubens** [comment]
Very Nice!

**Comment by fwaumans** [comment]
I have made a view in the database which stores the information about the etn fields: `vliz.datapaper_metadata_fields`. We can use the database as primary source for storing the metadata about the etn fields.

**Comment by peterdesmet** [comment]
Page updated at https://inbo.github.io/etn/articles/etn_fields.html. Still some corrections to be made (communicated by email), but a big improvement at least.

**Comment by peterdesmet** [comment]
Fields are now also ordered and a csv export is made available: https://inbo.github.io/etn/articles/etn_fields.html Closing this issue, rest can be tackled in separate issues.
