### ISSUE TITLE
Get deployments function to get deployments history

### ISSUE THREAD

**Issue by itstheclyde** [inbo/etn#115]
Hi I'm Clyde and I am working on all the data of Atlantic cod. I would like to get all the deployments history in Belgium so that I know how many receivers are available in each month. The get_deployments() only give me a portion of the deployments compared to what I can see in the ETN website. Does this function only gives a portion of the deployments metadata or it is supposed to give all the deployments history?

**Comment by peterdesmet** [comment]
Hi Clyde, see https://inbo.github.io/etn/reference/get_deployments.html: by default the function only returns open deployments. You can return all deployments by using:

```R
deployments <- get_deployments(open_only = FALSE)
```

Which currently returns 4420 results rather than 800.

Let me know if this is a counter-intuitive default setting.

**Comment by itstheclyde** [comment]
Hi Peter,

Thanks for the response. I did not notice this argument. I don't think it's counter-intuitive default setting. I think most people are interested only in open deployments rather than getting the whole deployment history. Thanks again!
