### ISSUE TITLE
Add owner_organization as parameter to get_tags() and get_receivers()

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#117]
As discussed in #110, it is considered useful to add `owner_organization` as a parameter to `get_tags()` and `get_receivers()`, to know which organization has financed these. I just checked the available values, and they seem to be controlled (i.e. there are no variations in spelling):

owner_organization | tags | receivers
-- | -- | --
AST | 143 | 65
CCMAR | 211 | 63
CEFAS | 94 | 56
CNR-IAS | 102 | 27
DDNI | 2 | 8
DTU-AQUA | 707 | 56
EGE-UNIVERSITY |   | 6
EULS | 54 | 5
HULL-IFI | 84 | 60
IHB-CAS |   | 92
IIM-CSIC | 25 | 12
ILVO | 10 |  
IMAR | 490 | 127
IMARES | 989 | 51
IMEDEA | 20 | 5
IMR | 268 | 55
IMSI | 6 | 2
INBO | 725 | 231
LOTEKLOAN |   | 3
MARBEC | 513 | 97
MARBIOL | 88 | 10
MBA | 482 | 26
MECKLENBURG-VORPOMMERN_RC | 150 | 8
MNHN | 342 | 51
NATURERESEARCHCENTRE | 70 | 16
NMNH_SOFIA | 2 |  
NMNHB |   | 1
NTNU-VM | 918 | 238
ODNATUUR |   | 28
PTN-MARE |   | 28
SCHOOLOFZOOLOGY |   | 7
SVN | 230 | 51
UNIVERSITY_GLASGOW | 33 | 13
UNIVERSITY_HAWAII |   | 16
UNIVERSITY_PERPIGNAN | 136 | 32
VAN-HALL-LARENSTEIN | 30 |  
VEMCO |   | 2
VLIZ | 532 | 165
VLIZ-CPOD |   | 1
NA | 1 |  

I propose that input values by the user are checked against **the combined list of owner_organizations in tags AND receivers** (i.e. the table above), with a help function `list_owner_organizations()`, rather that keeping owner_organization separate between tags and receivers (and thus needing two `list_*` functions). That might result in an input organization being correct, but not finding any tags, e.g. when doing:

```R
get_tags(owner_organization = "EGE-UNIVERSITY")
# No error, since "EGE-UNIVERSITY" is an owner_organization
# But also an empty dataframe, since EGE-UNIVERSITY has no tags
```

@PieterjanVerhelst @IPauwels is that OK?

**Comment by PieterjanVerhelst** [comment]
I agree 👍

**Comment by peterdesmet** [comment]
#112 was a duplicate. I'll try to summarize:

@PieterjanVerhelst @IPauwels and @jreubens are in favour of adding `owner_organization` as a parameter to `get_tags()` and `get_receivers()` with an implementation as discussed above.

@jreubens also agreed with [my comment](https://github.com/inbo/etn/issues/112#issuecomment-602057303) to **not** implement this:

> I wonder if it's typical enough as a use case to add it. I'm in favour of keeping it in the results you get back, but I wonder if it needs to be a parameter. Note that you can always do `get_receivers() %>% filter(owner_organization == "INBO")`. Also, you mention *brand use*, but that seems to be more related to the field `manufacturer`, no?

So, can you please give :+1:  to implement it as a parameter and 👎 if that is not necessary?

**Comment by PieterjanVerhelst** [comment]
I personally don't think we need any parameter into the functions if we can simply apply a filter (just to make the specific functions not too exhaustive).

**Comment by peterdesmet** [comment]
@PieterjanVerhelst great! So that would be a :-1: 😄

**Comment by IPauwels** [comment]
All fine by me..

**Comment by peterdesmet** [comment]
Ok, then I'll close this issue without further action.
