### ISSUE TITLE
Select multiple projects

### ISSUE THREAD

**Issue by PieterjanVerhelst** [inbo/etn#118]
How can I select and download data from multiple projects (animal or network) via the `get_detections()` function? I checked the manual, but couldn't find any info on this.

**Comment by damianooldoni** [comment]
based on [documentation of `?get_detections`](https://inbo.github.io/etn/reference/get_detections.html#arguments), you should just provide a vector with network/animal projects. Example:

```r
network_project_codes <- c("OTN-Tosenfjorden", "Artevigo")
test <- get_detections(my_conn,
                       network_project_code = network_project_codes,
                       limit = FALSE)
> test %>% 
    group_by(network_project_code) %>%
    count()
# A tibble: 2 x 2
# Groups:   network_project_code [2]
  network_project_code       n
  <chr>                  <int>
1 Artevigo             2075530
2 OTN-Tosenfjorden       13274
```

Does it make sense? Or do you mean something else? Thanks.

**Comment by PieterjanVerhelst** [comment]
@damianooldoni thanks! I was looking for a solution based in the `tidyverse` codings, but this is obvious much more convenient.

**Comment by damianooldoni** [comment]
No worries. Just for your info in case you will have to work with functions which don't support multiple values in one argument:

```r
library(purrr) # or library(tidyverse)
network_project_codes <- c("OTN-Tosenfjorden", "Artevigo")
test <- map_dfr(network_project_codes,
                function(prj) {
                  get_detections(my_conn, network_project_code = prj,
                                 limit = FALSE)
                }
)

test %>% 
  group_by(network_project_code) %>%
   count()
# A tibble: 2 x 2
# Groups:   network_project_code [2]
  network_project_code       n
  <chr>                  <int>
1 Artevigo             2075530
2 OTN-Tosenfjorden       13274
```
But, indeed, this is absolutely not needed in `get_detections`.
