### ISSUE TITLE
project filtering as function input

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#12]
@PieterjanVerhelst and @jreubens 
when requesting for data and addingnetwork or animal projects to the input, which type of input do you expect to use: `name` or `projectcode`?

Let me explain with an example: For the usage of for example the `get_tags` function,

```
get_tags(connection)  # all tags
get_tags(connection, animal_project = NULL)  # all tags
get_tags(connection, animal_project = "phd_reubens")  # tags of animal project phd_reubens
get_tags(connection, animal_project = c("phd_reubens", "homarus")  # tags of animal project phd_reubens and homarus
```
In the example, I use the `projectcode`. Is this the appropriate naming or will people use the `name`?

An example of the info about animal projects:
```
    id                   name        projectcode imis_dataset_id
1  616              rangetest          rangetest              NA
2   16        PhD Jan Reubens        phd_reubens            5846
3  599                Homarus            homarus              NA
4  632 Ocean Tracking Network                OTN              NA
5   22             2015 Dijle         2015_dijle            5872
6   21             2014 Demer         2014_demer            5871
7  621     2016 PhD Vergeynst 2016_phd_vergeynst            5875
8   18      2013 Albertkanaal  2013_albertkanaal            5868
```

**Comment by peterdesmet** [comment]
At least for the INBO datasets, we have standardized project names/codes:

id  | name               | project code
----|--------------------|--------------------
22  | 2015 Dijle         | 2015_dijle
18  | 2013 Albertkanaal  | 2013_albertkanaal
15  | 2012 Leopoldkanaal | 2012_leopoldkanaal
621 | 2016 PhD Vergeynst | 2016_phd_vergeynst
17  | 2015 PhD Verhelst  | 2015_phd_verhelst
622 | 2015 Fint          | 2015_fint
21  | 2014 Demer         | 2014_demer
20  | 2011 Rivierprik    | 2011_rivierprik

I would vote for `code` as input parameter, as that is less likely to change

**Comment by PieterjanVerhelst** [comment]
Currently, the `name` is used, but I prefer the` project code`, as it contains no capitals or spaces and is therefore more straightforward (less mistakes/errors will occur). @jreubens , what do you think?

**Comment by jreubens** [comment]
I also prefer the project_code

**Comment by stijnvanhoey** [comment]
`projectcode` it will be! closing
