### ISSUE TITLE
Quotes in tag_id for KAU-SLU

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#122]
KAU-SLU has tags with quotes in the `tag_id`, e.g. `"A180-1702-"-49684`. It is probably better to correct these.

**Comment by jreubens** [comment]
We are aware of this. Will be updated in the next days. But this project is not part of the datapaper...

**Comment by peterdesmet** [comment]
Great! No, I just noticed it. 😄 Closing this issue.
