### ISSUE TITLE
ETN field name typo

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#125]
@fwaumans two weird things I noticed in the file with all the field names you shared in https://github.com/inbo/etn/issues/113#issuecomment-688678735:

- [x] HYDROPHONE_CABLE_LENGHT: typo, should be HYDROPHONE_CABLE_LENGTH
- [x] RECEIVER: appears twice

**Comment by fwaumans** [comment]
These names appears in the headers of the tables in the webapplication.  The info is stored in a metadatatable in the database. 
HYDROPHONE_CABLE_LENGHT: I have corrected the typo in the database.
RECEIVER: can be a cpod hydrophone (cpod table in webapp) or a acoustic telemetry receiver.
I will make a view in the database that links the data in the metadatatable with the fields of the views and grant access to you.
