### ISSUE TITLE
Fields without a name in field_definitions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#127]
Reported by @fwaumans:

> Er zijn vier velden waar ik een probleem mee heb en waarvan de database_column_name leeg is.

- animal_view2:pk
- animal_view2:animal_id
- receivers_view2:telemetry_type: ?
- tags_view2: tag_id_alternative: thelma_converted_code?

@fwaumans 

- I noticed it is the other way around: the `database_column_name` is populated, but `field` is empty. Can you confirm?
- I am using `field` on https://inbo.github.io/etn/articles/etn_fields.html, because I assumed that is the field name as it appears in the animal_view2, receivers_view2, etc. view? Is this correct?

**Comment by peterdesmet** [comment]
activation_date in tags_view2 seems to be dropped too

**Comment by fwaumans** [comment]
Indeed, the database_column_name is populated and the field is empty.
> I am using field on https://inbo.github.io/etn/articles/etn_fields.html, because I assumed that is the field name as it appears in the animal_view2, receivers_view2, etc. view?  
Correct

**Comment by fwaumans** [comment]
For the animal view. I don't understand the difference between pk and animal_id

| view/table field   (animals) | suggested_field |                                   |   |   |
|------------------------------|-----------------|-----------------------------------|---|---|
| id_pk                        | pk              | primary key (autoincrement field) |   |   |
| id_pk                        | animal_id       | primary key (autoincrement field) |   |   |
| animal_id                    | animal_label    | unique lable given by researcher  |   |   |

**Comment by fwaumans** [comment]
Receivers
What is the difference between `telemetry_type` and `application_type`?

**Comment by fwaumans** [comment]
Tags:
I will rename the field `thelma_converted_code`   by `tag_id_alternative`

**Comment by peterdesmet** [comment]
> Tags: I will rename the field `thelma_converted_code`   by `tag_id_alternative`

:+1: `tag_id_alternative` should be the 3rd field, between `tag_id` and `telemetry_type`

> Receivers: What is the difference between `telemetry_type` and `application_type`?

`application_type` is a high level distinction (populated with `cpod` or `acoustic_telemetry`), but `telemetry_type` seems never populated. I'm not sure what is should be populated with (@jreubens @PieterjanVerhelst), but for now it can be added to the list of fields without definition.

> animal view. I don't understand the difference between pk and animal_id

The field that was in the old views called `animal_id` should be called `animal_label` ("Identification code that uniquely identifies each animal, as specified by the researcher.") and 2 fields should be based on `id_pk`: the `pk` and `animal_id`. There is no difference between these, but for consistency with tags and receivers we opted to have a `pk` and an `_id` field. For animals these just contain the same content.

**Comment by fwaumans** [comment]
Ok for tags and animals.

About the difference between telemetry_type and application_type (receivers).
I think for application_type the two different values should be `telemetry ` (=tracking of tagged (known) animals' ) or `cpod` (=tracking of non-tagged (not-known) animals (porpoises)). 

I case of telemetry you can specify the type of telemetry (telemetry_type):  `Acoustic`, `Archival`, `Satellite`, `PIT`, `Radio`.  At this moment we can only store acoustic telemetry data in the ETN database.

**Comment by jreubens** [comment]
@fwaumans, @peterdesmet  telemetry_type is indeed specifiying which telemetry technology you are using (i.e. acoustic, archival, satellite, ...) But I don't see this column on receiver level, only on tag level...Where are you looking?

**Comment by fwaumans** [comment]
Tags: `tag_id_alternative` was added
Receivers: the value 'acoustic' was completed in the field `telemetry_type`
Animals; `animal_id `and `id.pk` were adjusted

**Comment by peterdesmet** [comment]
Thanks! I noticed `step1_duration` jumped in front of `step1_power` in tags, can you revert that to `power`, then `duration`?

**Comment by fwaumans** [comment]
Done!

**Comment by peterdesmet** [comment]
Thanks, fix now on website.
