### ISSUE TITLE
Maintain a csv export of field_definitions view

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#129]
https://inbo.github.io/etn/articles/etn_fields.html is a human readable overview of the fields and definitions, but I think it would be useful to also provide this as a csv file (which could additionally be deposited on Zenodo).

@damianooldoni it is a bit unclear to me where this file should be stored, see https://r-pkgs.org/data.html. It's not in `data` as it's not binary R data. So, is it `inst/extdata` or `data-raw` then?

**Comment by peterdesmet** [comment]
Implemented in `inst/extdata` in 7e087ed7, but feedback on best practice still welcome.

**Comment by damianooldoni** [comment]
First of all, thanks @peterdesmet for this precious documentation work!

About che choice of using `inst` directory: YES.
I am doubting about the subdirectory `extdata`. After googling and checking other packages as rgbif, I think we could best make use of `assets` subdirectory for this kind of data. 
Example: https://github.com/ropensci/rgbif/blob/master/inst/assets/typestatus.csv
