### ISSUE TITLE
Create function to download data for publication

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#130]
Create function that replicates functionality of https://github.com/inbo/etn-occurrences/blob/master/src/1_download.Rmd

`download_dataset()`

## Input

- `directory`: where files should be put
- `animal_project_code`
- `scientific_name` (to filter e.g. `sync tag` out)
- ~~`cut_off_date`: is this necessary? **see below: at least not for deployments**. Undecided for detections~~

## Output

- `animals.csv`: associated with that `animal_project_code`
- `tags.csv`: associated with those animals
- `detections.csv`: associated with that `animal_project_code`. Also extract `network_project_codes`
- `deployments.csv`: all associated with set of `network_project_codes`
- `receivers.csv`: all found in deployments
- `datapackage.json`: metadata file describing those records
- A summary of the export in the terminal

**Comment by peterdesmet** [comment]
@PieterjanVerhelst (in conversation in Google spreadsheet) says cut-off date for deployments not necessary:

> Een einddatum geeft goed weer wanneer een netwerk de laatste keer werd uitgelezen en is bijgevolg een indicatie voor zijn 'activity', dus zou dit zo laten.

**Comment by peterdesmet** [comment]
@jreubens @PieterjanVerhelst will it ever be useful to download sync/sentinel data for an animal project as a dataset?

**Comment by peterdesmet** [comment]
This is now implemented in #132, see online function documentation at https://inbo.github.io/etn/reference/download_dataset.html.

@jreubens @PieterjanVerhelst The above question regarding sync/sentinel data remains. If a scientific_name is not provided, the function will download all data including sync/sentinel data. This can be a lot (for a default option).

**Comment by PieterjanVerhelst** [comment]
@jreubens we think it would be better to put sync/sentinel/range_test tags and data under a separate project. This would make those 'sub' datasets better traceable. For instance, researchers may be interested in a range test rather than the fish detections. Putting them in another project will make their existence clear.

**Comment by jreubens** [comment]
@PieterjanVerhelst; @peterdesmet  I wouldn't put this type of data under a separate project.
It is often part of the analyses you perform in the framework of you species data as it is a proxy for environmental factors influencing your detectability...
However, I do agree that you are not always interested in this part of the data and perform the analysis separate from your species analysis. Can you add 'tag_type' in the function? THis is a compulsory field if you create a new tag and specifies if it is an animal, sync, built-in,.... thus than you can easily filter.

**Comment by peterdesmet** [comment]
Jan, the issue is a bit that when publishing a dataset: do you want both included or is it easier for users if those are separate datasets (that link to each other)?

**Comment by jreubens** [comment]
will depend on the context... but isn't this a choice researchers should have?

**Comment by peterdesmet** [comment]
Yes, and by offering two datasets/projects, I think the choice is easier for them. The question came up in context of the current data paper. Until now I've always hear to _not_ included the sync data, but keep it to the biological data. But then we need another avenue to (maybe later) publish the sync data, e.g. as a separate project.

**Comment by peterdesmet** [comment]
This function is now implemented, sync tags will be returned by the function, but to better describe methodology/allow users to download biological vs sync data, those will be moved to separate projects.
