### ISSUE TITLE
Seperate project for sync/sentinel/range_test tags 

### ISSUE THREAD

**Issue by PieterjanVerhelst** [inbo/etn#134]
@jreubens we think it would be better to put sync/sentinel/range_test tags and data under a separate project. This would make those 'sub' datasets better traceable. For instance, researchers may be interested in a range test rather than the fish detections. Putting them in another project will make their existence clear.

_Originally posted by @PieterjanVerhelst in https://github.com/inbo/etn/issues/130#issuecomment-709400070

**Comment by peterdesmet** [comment]
Discussion was continued in #130, but eventually agreed with @jreubens to move sync tags to separate project/dataset. This needs to be done for:

- [ ] `2010_phd_reubens_sync`
- [ ] `2012_leopoldkanaal_sync`
