### ISSUE TITLE
Error for summarize

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#137]
When using `download_dataset(con, "2011_rivierprik")` I'm getting an error:

```R
Error in summarize(., min(as.Date(date_time))) : 
  could not find function "summarize"
```

Even though that function is listed in importFrom (see https://github.com/inbo/etn/commit/6d6f0f444a4a20fd186106788e6260a08b6c6599). @damianooldoni care to take a look what might be causing this?

**Comment by damianooldoni** [comment]
I cannot reproduce your error. I am working on master and everything is working fine. Can you give me more details about the error?

Try maybe to restart R, reinstall etn, loading it and then auto completion should work while typing `summarize()`.

**Comment by peterdesmet** [comment]
I must have been using the wrong installation. Clean install works now.
