### ISSUE TITLE
Make searching on codes case insensitive

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#140]
Since not all project_codes are using the same capitalization (`JSATS-PalmaBay-2019`, `2015_Albertkanaal_VPS_Ham`), I'm suggesting to make searching on codes case insensitive, so that you can e.g. search for the following animal_project_codes:

```
2010_PhD_Reubens
2010_phd_reubens
2010_PHD_REUBENS
```

To query data for `2010_phd_reubens`. This would then apply to:

- animal_project_code
- network_project_code
- ~receiver_id~
- station_name
- ~tag_id~

@jreubens @damianooldoni @IPauwels @PieterjanVerhelst Please let me know with thumbs up/down if you think this is a good idea (or leave a comment).

**Comment by PieterjanVerhelst** [comment]
@peterdesmet this is about the search functionality in the data publication? If so, I agree for the project codes but would also do this for the station names.

**Comment by peterdesmet** [comment]
This is about search functionality using ETN functions:

    get_animals(animal_project_code = “VALUE”)
    get_animals(animal_project_code = “value”)

Ok, could implement it for station names too.

**Comment by peterdesmet** [comment]
This is implemented in #144
