### ISSUE TITLE
Avoid arising warning in summary for empty projects in download_dataset()

### ISSUE THREAD

**Issue by damianooldoni** [inbo/etn#141]
While trying to download data of a project, `2018_Iller`, I get an additional warning at the end:

```r
Warning messages:
1: In min.default(numeric(0), na.rm = FALSE) :
  no non-missing arguments to min; returning Inf
2: In max.default(numeric(0), na.rm = FALSE) :
  no non-missing arguments to max; returning -Inf
```

This is due to the fact that the project is empty, so no min or max date for `detections` can be returned:

```
message("* first date of detection:     ", detections %>% summarize(min(as.Date(.data$date_time))) %>% pull())
message("* last date of detection:      ", detections %>% summarize(max(as.Date(.data$date_time))) %>% pull())
````

I would fix it by adding a small `if (nrow(detections) == 0) {}- else{}` to embed these two lines of codes.

@peterdesmet: is it ok for you?

**Comment by peterdesmet** [comment]
Yes, good catch.

**Comment by damianooldoni** [comment]
Fixed in https://github.com/inbo/etn/commit/1bace2b513c3fd007e834a9a970113764e9ca9a7

**Comment by damianooldoni** [comment]
@peterdesmet, this issue has been solved. We can close it, isn't?

**Comment by peterdesmet** [comment]
Yes indeed.
