### ISSUE TITLE
Add tags_view2.activation_date to field_definitions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#148]
In field descriptions there is an empty `tags_view2` field at [line 213](https://github.com/inbo/etn/blob/master/inst/assets/etn_fields.csv#L213). I think that should become `activation_date` with order `13`. That is how it appears in the `datapackage.json` and the actual view (even though it is only populated for 515 of the 11,434 tags):

```
12 status <chr>
13 activation_date <dttm>
14 battery_estimated_life <chr>
15 battery_estimated_end_date <dttm>
16 sensor_type <chr>
```

@aubrivliz can this be updated in `vliz.field_definitions`?

**Comment by peterdesmet** [comment]
Note that in `deployments_view2` there is a field called `activation_date`**`_time`**. Not entirely sure why we decided on date here (but other field have it too: `ar_battery_installation_date`

**Comment by aubrivliz** [comment]
@peterdesmet is this still relevant or can this be closed?

**Comment by peterdesmet** [comment]
No, the views can be deleted, see #156.
