### ISSUE TITLE
accelerometer_samples_per_second: integer or double

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#149]
I noticed the date type of the `tags_view2` field `accelerometer_samples_per_second` has changed from `integer` to `double`: https://github.com/inbo/etn/commit/9bfb4298ecaf12c58576b8b068461f0444384454

Also in the view return I get: `accelerometer_samples_per_second <dbl>`

@jreubens can it be confirmed this is intentional? If so, I need to update the `datapackage.json`.

**Comment by jreubens** [comment]
@peterdesmet this is intentional as we can numbers with a decimal value
