### ISSUE TITLE
controlled vocabulary for `receiver_status`

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#15]
As we aim to provide receiver status as an input argument of the function `get_edployments`, we have to know the possible inputs (or have access to query these options).

The options I can currently find are:
```
           receiver_status
1                Available
2                     Lost
3                   Broken
4                   Active
5 Returned to manufacturer
```
I do not think the normal user has access rights to the original table with the receiver_status options, but having the controlled vocabulary hard coded in the package won't be that bad I assume as this won't changes regularly?

**Comment by stijnvanhoey** [comment]
Or do we just want to have the options: `active` (subset of the active only) versus ALL?

**Comment by jreubens** [comment]
This won't change often indeed.
by default a receiver is available (if not used in a deployment) or active (if in a deployment).
the other status options the user had to select themselves.
i would include them all, if you quickly want to know something on a specific status

**Comment by stijnvanhoey** [comment]
ok, receiver_status can be one or multiple options of `c("Available", "Lost", "Broken", "Active", "Returned to manufacturer")`

**Comment by PieterjanVerhelst** [comment]
I think that would be best.

**Comment by stijnvanhoey** [comment]
handled by https://github.com/inbo/etn/commit/66e4ec81653bfcafb7d22dfb060dd5d6ed81a639 closing here
