### ISSUE TITLE
Add receivers_view2.telemetry_type to field_descriptions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#150]
In field descriptions there is an empty `receivers_view2` field at [line 168](https://github.com/inbo/etn/blob/master/inst/assets/etn_fields.csv#L168). I think that should become `telemetry_type` with order 4, with the order of the other fields shifting down (4 becomes 5 etc, all the way to 26). The datatype is `string`. The field is already listed in the view and `datapackage.json`.

@aubrivliz can this be updated in `vliz.field_definitions`?

**Comment by peterdesmet** [comment]
@aubrivliz @jreubens the result of `get_receivers()` has the field `telemetry_type`, which only had the value `acoustic`. Is this field still useful (note that pit can also have receivers)? If so @aubrivliz, how do I get this value using the new model?

**Comment by aubrivliz** [comment]
@peterdesmet for acoustic this has been changed to `receiver_type` to get the acoustic receivers and the cpod receivers (this table is also used for the cpod receivers). When we add PIT in the future we will have a new table `receivers` in a new schema for pit.

**Comment by peterdesmet** [comment]
Ok, the field `receiver_type` (mapped to `application_type`) has always been there indeed, with the values `cpod` and `acoustic_telemetry`. I draw a number of conclusions:

- The field `telemetry_type` should no longer be returned by the function: it does not provide useful information.
- As a design principle, functions should always return the same data.frame structure (no matter the scope). If the structure is different for a different scope, then it should be a new function. It seems that will be the case for PIT, so maybe `get_receivers()` should already become `get_acoustic_receivers()`?

**Comment by aubrivliz** [comment]
@peterdesmet is this still relevant or can this be closed?
