### ISSUE TITLE
Short controlled names for scopes

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#153]
@aubrivliz @jreubens can you give us a list of the different (new) scopes, so we can come up with good short names for them such as `pit`, `acoustic`, `dst`. These names will be important for function names or parameters.

**Comment by jreubens** [comment]
@peterdesmet  I suppose you refer to the different contexts here.
What it will be:
- Acoustic Telemetry
- Archival Data
- Acoustic-Archival
- Underwater Acoustics
- Passive Integrated Transponders
Later others can be added

**Comment by peterdesmet** [comment]
Great, since those names are quite long, can you suggest shorter, lowercase values? Except for `pit` I won't make an attempt, because it is unclear to me what those contexts mean and how they are different.

**Comment by peterdesmet** [comment]
For now, the scopes are `acoustic` and `archival` and those are part of the function names. Closing.
