### ISSUE TITLE
Error when connecting to the database ("connect_to_etn" function)

### ISSUE THREAD

**Issue by aspillaga** [inbo/etn#163]
I am getting the following error when I try to connect to the database using the "connect_to_etn function":

Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Data source name not found and no default driver specified 

I am using a MacOs and R version 4.0.4.

**Comment by peterdesmet** [comment]
It seems you are connecting from your local computer. That is unfortunately not possible, due to connection restrictions to the ETN database. The package only works on https://rstudio.lifewatch.be/ (which is in behind the same firewall as the database). A login can be requested at http://www.lifewatch.be/etn/contact.

In the future, we hope to use a different way of connecting to ETN (over webservices), allowing the package to be used on any computer.

**Comment by aspillaga** [comment]
Thanks for the answer! Before I tried with my local computer, I did try to work with the remote server, but I was not able to install the "etn" package. I get an error related to the compilation of the "odbc" package.

**Comment by PieterjanVerhelst** [comment]
@aspillaga have you tried the code I sent ou on the remote server? Normally that should work.

**Comment by aspillaga** [comment]
Thanks @PieterjanVerhelst! It worked! I guess that some dependencies were missing or had to be updated...

I paste here Pieterjan's code in case is useful for anyone:

# Install and load packages
install.packages("devtools")
install.packages("digest")
#install.packages("processx")
devtools::install_github("inbo/etn")

**Comment by jonasmortelmansvliz** [comment]
Hi, thanks!
I actually had the same issue simultaneously.
However - Pieterjan's code was not helping me...
In my case, library(etn) is running just fine.

I am working on remote server (in VLIZ), via rstudio.lifewatch.be, and trying to connect with my lifewatch.be/etn credentials.
I am getting an error: "Error: nanodbc/nanodbc.cpp:983: 00000: [unixODBC]fe_sendauth: no password supplied"

Anybody experienced similar error?

**Comment by PieterjanVerhelst** [comment]
I would guess that you either did not add your password or put a wrong one.  Did you make connection like this?
```
my_con <- connect_to_etn("email",
                         "password")
```

**Comment by aspillaga** [comment]
Hi! I am having a similar problem as @jonasmortelmansvliz. When I try to connect to the database I get this error:

Error: nanodbc/nanodbc.cpp:983: 00000: [unixODBC]FATAL: password authentication failed for user "[my actual email]"

I am using the same email and password I use at the ETN data portal and the Rstudio server.

**Comment by PieterjanVerhelst** [comment]
@aspillaga @jonasmortelmansvliz the password is different than the one you use for the ETN data portal. I would think you got the relevant password when registering at the VLIZ Rstudio server.

**Comment by jreubens** [comment]
hi,
try this
Sys.setenv(PG_LOGIN = "jonas.mortelmans@vliz.be", PG_PASS = "***")
my_con <- connect_to_etn(Sys.getenv("PG_LOGIN"), Sys.getenv("PG_PASS"))
------------------

*** replace by real password

**Comment by aspillaga** [comment]
Hi! 
@PieterjanVerhelst I use the same username and password for all the different logins, so I guess that they should work... 
@jreubens this is not working either...

**Comment by PieterjanVerhelst** [comment]
@aspillaga, I got the password needed to connect to ETN via the VLIZ Rstudio server from VLIZ and don't think I could change it myself (but it's a long time ago, so can be wrong). Better to check with @jreubens if your login & password are valid to connect. I am quite sure that will be the problem holding your from downloading the data.

**Comment by aspillaga** [comment]
Thanks @PieterjanVerhelst! You were right. I needed the specific password to access the ETN database, which I had to request from the database administrators. With this password, I was finally able to access the data.

**Comment by damianooldoni** [comment]
That's good news @aspillaga. 
@jonasmortelmansvliz: could you please check if this helps you as well and let us know?

**Comment by jonasmortelmansvliz** [comment]
Yes!
same for me, the password given by database administrator did the job ;-) 
thanks
