### ISSUE TITLE
Error in current version of package: projects_view2 does not exist

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#175]
@jreubens reported:

> Krijg deze error: Error: <SQL> 'SELECT DISTINCT project_code FROM vliz.projects_view2 WHERE project_type = 'network''
>  nanodbc/nanodbc.cpp:1587: 42P01: ERROR: relation "vliz.projects_view2" does not exist;
> 
> Error while executing the query

@aubrivliz was that view removed?

**Comment by aubrivliz** [comment]
@peterdesmet, all the views are under the "acoustic" schema, so acoustic.projects_view2 should work fine.

**Comment by peterdesmet** [comment]
@jreubens, I think you can resolve this issue by updating to the latest version of the package:

```R
devtools::install_github("inbo/etn")
# choose 3: None for updates
library(etn)
con <- connect_to_etn(Sys.getenv("userid"), Sys.getenv("pwd"))
get_projects()
```

**Comment by jreubens** [comment]
ISsue persists..
> get_projects()
Error: <SQL> '  SELECT *
  FROM vliz.projects_view2
  WHERE
    'True'
    AND 'True''
  nanodbc/nanodbc.cpp:1587: 42P01: ERROR: relation "vliz.projects_view2" does not exist;
Error while executing the query 

It still refers to 'view2' .. anything else I can do?

**Comment by peterdesmet** [comment]
@jreubens the fact that your code refers to `vliz.projects_view2` indicates that you are still using an outdated version of the package. Try again with:

```
devtools::install_github("inbo/etn", force = TRUE)
```

**Comment by peterdesmet** [comment]
Our browse to your packages and remove "etn" before installing again.

**Comment by peterdesmet** [comment]
@jreubens is this issue resolved for you?

**Comment by jreubens** [comment]
yes it is resolved! I'll close it

**Comment by jreubens** [comment]
done
