### ISSUE TITLE
Extend the `animals_view` (and others) on database level wit the `projectcode` column

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#18]
As decided in #12 to use the `projectcode` to enable the user to subselect specific projects, it would be more convenient to have the `projectcode` columns added to the views for which this selection is relevant and when it is possible:

*  [x]  deployments_view  
*  [x]  animals_view  
* [x] tags  *possible?!?*
* [x] receivers *possible?!?*
* [x] detections_view

**Comment by bwydoogh** [comment]
@jreubens Yes, I'm here 🙂.
For `tags` and `receivers` there is no link with a project, so I cannot add it there.
I've added the `code` to the `animal_view`.

**Comment by stijnvanhoey** [comment]
@bwydoogh thanks!

**Comment by stijnvanhoey** [comment]
for the animals view, the obsolete section (join inside the R-function) is excluded, see https://github.com/inbo/etn/commit/74ece79aa7b51041edf8dc3df2ec0e17f649d6ea

closing here.
