### ISSUE TITLE
Why do many archival_tag not have an id_code?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#182]

**Comment by jreubens** [comment]
If I'm correct archival tags never have an id_code, but only a serial. no distinction is made between both in archival tags

**Comment by PieterjanVerhelst** [comment]
Indeed, they don't send out an ID that can be picked up by a beacon. So there is only a serial number of the product, the archival tag.

**Comment by peterdesmet** [comment]
The `archival.tags` table does have an `id_code` field however and when populated, it is different from the serial number:

<img width="559" alt="Screenshot 2021-10-04 at 10 29 09" src="https://user-images.githubusercontent.com/600993/135818708-94932736-47ba-4aa0-bb4c-e3be43b5b6d6.png">

If that field does not make sense, it **should be removed**. It was confusing to me, because I implemented it as a parameter for `get_archival_tags(archival_tag_id = "")` (cf. `get_acoustic_tags(acoustic_tag_id = "")`)

**Comment by peterdesmet** [comment]
The field should stay, as it is used for **acoustic** archival tags. Model should likely be changed though, see #192. Moving issue to new milestone.

**Comment by peterdesmet** [comment]
There is not action item in this issue, closing.
