### ISSUE TITLE
species subsetting as function input

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#19]
@PieterjanVerhelst and @jreubens when subsetting on species name, I assume you'll provide a number of scienitific names as these seem to be provided, whereas common_name not:
```
> scientific_name
 [1] "Gadus morhua"         "Sentinel"             "Homarus gammarus"    
 [4] "Alosa fallax"         "Built-in"             "Anguilla anguilla"   
 [7] "Lampetra fluviatilis" "Salmo salar"          "Squalius cephalus"   
[10] "Silurus glanis"       "Petromyzon marinus"   "Rutilus rutilus"     
[13] "Platichthys flesus"   "Cyprinus carpio"      "Sync tag"            
[16] "salmo salar"         
> common_name
[1] NA             "Atlantic cod" "Fint"      
```

ok to filter on the scientific names?

**Comment by PieterjanVerhelst** [comment]
@jreubens so we can change the names into lower case letters with underscore?

**Comment by stijnvanhoey** [comment]
lowercase, ok; see #21 for the lower_case way of working...

**Comment by peterdesmet** [comment]
In my opinion scientific names in ETN DB should **not** be changed to "lower_case", those names have to be written as proper scientific names (`Salmo salar`). Any function accepting scientific names as input, should also expect properly written scientific names _and_ as @jreubens suggests Aphia IDs, which are an even more stable identifier.

**Comment by jreubens** [comment]
lowercase for me certainly ok!

**Comment by jreubens** [comment]
ok, I hadn't seen comment of Peter when I accepted lower case...
Don't know whether this has been implemented now... But To my opinion we should change to Aphia asap...

**Comment by stijnvanhoey** [comment]
For the moment, no filtering is done and names are compared as such. 

From the package side, we can use the `wm_records_taxamatch(name = '...')` [worrms function](https://github.com/ropensci/worrms) to check incoming names from the user, but this only makes sense if we can use these worms-names to query the database.

hence, I do think, this should be covered on the database level first...

**Comment by peterdesmet** [comment]
Update on this issue: the function `get_animals()` is the only one with a `scientific_name` parameter. Input values are compared with all scientific names in the animals view (using [`list_scientific_names()`](https://inbo.github.io/etn/reference/list_scientific_names.html)) before running the query, so an error can be returned if a name is not recognized:

```R
get_animals(scientific_name = "Salmo salaar")
Error: Invalid value(s) for scientific_name argument.
Valid inputs are: Rutilus rutilus, Platichthys flesus, Labrus bergylta, Built-in, Dicentrarchus labrax, Perca fluviatilis, Limanda limanda, Anguilla anguilla, Diplodus sargus,  Salmo trutta, Pleuronectes platessa, Gadus morhua, Silurus glanis, Homarus gammarus, Salmo trutta, Mustelus asterias, Epinephelus marginatus, Alosa fallax, Salvelinus alpinus, Palinurus elephas and others...
```

If a name is written incorrectly in the database, it will also incorrectly be returned as a valid value, but this is the best we can do right now. Closing this issue.

Note: `aphia_id` is still empty for all names, but since that is a database task, I'm not going to add it as an issue here.
