### ISSUE TITLE
New model for tags

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#192]
@jreubens and I discussed the data model on the phone and we think it should be updated so that:

1. Table `tag_device` should only contain unique serial numbers: one device = one serial number = one row
2. (New) table `tags` contains one or more identifiers associated with the `tag_device`. It is a combination of the current tables `acoustic.tags` and `sensor.tags`, but also allows to store acoustic archival tags. This table also contains the `type` (archival/acoustic)  and `subtype`, which are no longer associated with `tag_device` (since a tag_device can have more than one type).

Examples:

- **Acoustic tag**: 1 `tag_device` row - 1 `tag` row, with `type=acoustic` and an `acoustic_tag_id` that can be found in detections.
- **Archival tag**: 1 `tag_device` row - 2 `tag` rows, with `sensor_type=depth` and `sensor_type=temp` and both with `type=archival`. There are no associated detections, only associated readings.
- **Acoustic archival tag**: 1 `tag_device` row - 4 `tag` rows, 2 `archival` ones (for both sensors) and 2 `acoustic` ones, with different `acoustic_tag_id`s. There are associated detections (for both `acoustic_tag_id`)  and readings.

Schema:

```
                  ┌ tag (depth)
animal - tag_device
                  └ tag (depth)
```

@aubrivliz Note that this is just an idea that should be discussed further. It should not be implemented yet.

**Comment by PieterjanVerhelst** [comment]
Here I am a bit confused, because an acoustic tag can have sensors as well. So is the mentioned `sensor-tag` here an acoustic transmitter with sensors or an archival tag (basically only existing of sensors, as it has not an 'emitting' part; it is not a transmitter, but a datalogger).

**Comment by PieterjanVerhelst** [comment]
ok, that is clear. No further questions or suggestions, except that it would indeed be good common practice to fill in the full sensor type (so e.g. 'pressure' instead of 'P') to make it more self-explanatory.

**Comment by PietrH** [comment]
@peterdesmet Is it ok to close this?

**Comment by peterdesmet** [comment]
Yeah, I think so
