### ISSUE TITLE
Authentication failed while trying establishing connection

### ISSUE THREAD

**Issue by damianooldoni** [inbo/etn#20]
I am busy developing code with @stijnvanhoey.
While testing function `connect_to_etn(user, password), I get  this error message:

> Error: nanodbc/nanodbc.cpp:950: 28P01: [unixODBC]FATAL: password authentication failed for user "damianoo" 

I am using same credentials as those ones for RStudio server. Any idea? 
Thanks!

**Comment by bwydoogh** [comment]
@damianooldoni There doesn't exist a user called `damianoo`. You need to use `damiano.oldoni@inbo.be` as username. I assume you received the password belonging to that user? If not, let me know and I send you an e-mail.

**Comment by damianooldoni** [comment]
Thanks @bwydoogh . Bart Vanhoorne fixed it, it seems. Thanks for your support.
