### ISSUE TITLE
get_acoustic_deployments(): additional fields needed?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#206]
The following fields are available in the table `acoustic.deployments`, but were **not** returned by the original `get_deployments()`. Some of them are available in the application. @jreubens @PieterjanVerhelst can you have a look and tell me if any of these need to be added to the data frame returned by `get_acoustic_deployments()`?

field | shown in app | example | remark
--- | --- | --- | ---
dep.check_complete_time | CHECK_COMPLETE_TIME | _all empty_ | **useful?**
dep.voltage_at_deploy | - | 3.6 | **useful?**
dep.voltage_at_download | VOLTAGE_AT_DOWNLOAD | 3.3 | **useful?**
dep.location_description | LOCATION_DESCRIPTION | Wilfordkaai 5, Temse; aan meerpaal nabij brug | **useful?** This is different from STATION_DESCRIPTION (which is taken from LOCATION_NAME
dep.date_created | - | 2018-01-18 12:43:54 | keep internal
dep.date_modified | - | 2018-05-28 08:27:30 | keep internal
dep.distance_to_mouth | DISTANCETOMOUTH | 874 | **useful?**
dep.source | - | source excel inbo | keep internal
dep.acousticreleasenumber | ACOUSTIC_RELEASE_NUMBER | 4023 | only include for cpod
dep.hydrophonecablelength | HYDROPHONE_CABLE_LENGTH | 1 | only include for cpod
dep.recordingname | RECORDING_NAME | \archive\other_platforms\b&k\COVID-19\20200429_Zeekat\Heinkel 111 | only include for cpod, view also has a calculated resolved_acousticreleasenumber
dep.hydrophonesensitivity | HYDROPHONE_SENSIVITY | -170 | only include for cpod
dep.amplifiersensitivity | AMPLIFIER_SENSIVITY | 3.16 mV | only include for cpod
dep.sample_rate | SAMPLE_RATE | 48000 | only include for cpod
dep.external_id | - | _all empty_ | keep internal

**Comment by jreubens** [comment]
agree with @PieterjanVerhelst

**Comment by PieterjanVerhelst** [comment]
The moment of deployment can be used to analyse if fish were not detected if a deployment was simply absent. However, if I understand correctly, `dep.deploy_date_time` is actually more suited for that, so okay to keep this field in and leave `dep.date_created` out.
