### ISSUE TITLE
get_tags(): field names for resolution, unit, accuracy, range_min, range_max

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#208]
I have now included 5 sensor-specific fields (resolution, unit, accuracy, range_min, range_max) in the data frame returned by `get_tags()`. These are fields that are present in `archival.sensor` but not in `acoustic.tag` (so they will be `NA` for acoustic tags). The 5 fields are shown in the context of other returned fields below, in **bold**.

@jreubens @PieterjanVerhelst 

1. If these are specific _sensor_ fields, I wonder if we should have there name start with `sensor_`
2. For the `range_min`, `range_max` fields, I wonder if they should not occur after the already present `sensor_range`

field | remark
--- | ---
... | ...
manufacturer | 
model | 
frequency | 
status | 
activation_date | 
battery_estimated_life | 
battery_estimated_end_date | 
**resolution** | sensor_resolution?
**unit** | sensor_unit?
**accuracy** | sensor_accuracy?
**range_min** | sensor_range_min?
**range_max** | sensor_range_max?
sensor_slope | 
sensor_intercept | 
sensor_range | 
sensor_transmit_ratio | 
accelerometer_algorithm | 
accelerometer_samples_per_second | 
... | ...

**Comment by PieterjanVerhelst** [comment]
1. Yes, these are sensor-specific fields
2. I would remove `sensor_range` and keep your suggested, separated fields for min and max

Is this table for a specific sensor or for an archival tag with multiple sensors? Shouldn't there be a field indicating what type the sensor is (temp, pressure, light etc.)?
`frequency` is the time interval the sensor records a measurement, I guess?
