### ISSUE TITLE
Ghost detections for demer_2014

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#220]
An animal in 2014_DEMER (A69-1601-28296, 384, Silurus glanis) has a single detection on 2020-09-07 17:25:22 by VR2W-126349 (acoustic project MOBEIA). As a result, it alters the expect test results for `download_acoustic_dataset()`.

@IPauwels says this is outside temporal and spatial range, and thus a ghost detection.

This records should be flagged as a ghost detection? How can we do that? Can animals or tags have a closing date?

**Comment by peterdesmet** [comment]
Once solved, revert b856d82.

**Comment by PieterjanVerhelst** [comment]
Agreed.

**Comment by PieterjanVerhelst** [comment]
Yes, but I think this issue needs a much wider elaboration and therefore I would suggest to do this all at once, instead of implementing a part now and the rest later. Just to be sure we won't have to undo previous work.
