### ISSUE TITLE
Make station_name case insensitive?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#222]
This is currently disabled for `get_acoustic_deployments()` and `get_acoustic_detections()`, because it slows down `get_acoustic_detections()` considerably. That could maybe improved if `detections_limited` always returns `station_name` in uppercase?

@PieterjanVerhelst how important is it that this parameter is case insensitive?

**Comment by PieterjanVerhelst** [comment]
Not that important imo. I think it is good practice to always use the exact names (taking into account lower and upper case) in coding.

**Comment by peterdesmet** [comment]
Thanks @PieterjanVerhelst, then we will not implement case insensitive station name. Closing issue.
