### ISSUE TITLE
`get_tag` handling of the animal_project choice

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#23]
When I check the tags data coupled with the `projectcode` to enable searches using a set of animal project codes:

```
  "SELECT tags.*, animals.projectcode
      FROM vliz.tags
        LEFT JOIN vliz.animal_tag_release ON (animal_tag_release.tag_fk = tags.id_pk)
        LEFT JOIN vliz.animals_view animals ON (animals.id_pk = animal_tag_release.animal_fk)
  "
```
(@bwydoogh, I do think I do this correct?)

I do get (on my account) 1403 NA values for the `projectcode`. @PieterjanVerhelst or @jreubens when users request the data and the default is all projects (`get_tags(connection)` is by default all projects), should this result in *all projects and ALL not-matched tags* or *only those tags that can be linked to an animal project* (according to the query defined here)?

**Comment by stijnvanhoey** [comment]
Additional question, can a tag be linked to > 1 animal project as well? I get 45 records more when adding the `project_code` to the tags table.

**Comment by PieterjanVerhelst** [comment]
It depends where those NAs come from. I suspect from range tests? Could you provide some example records of the NAs here?
Yes, it can occur a tag is retrieved from an animal and used in another animal in another project. For example, tag `29920` has been used in `2012 Leopoldkanaal` and `2013 Albertkanaal`.

**Comment by PieterjanVerhelst** [comment]
I think all tags should have a project code as they are linked to a certain project. Therefore, it is logic to give by default _only those tags that can be linked to an animal project_ .

**Comment by stijnvanhoey** [comment]
Closing here, as the current version implements this as such: tags/transmitters without a project are not returned to the user.
