### ISSUE TITLE
get_tags() failure to retrieve archival and acoustic-archival data

### ISSUE THREAD

**Issue by cfmuniz** [inbo/etn#243]
I am having issues retrieving tag data other than acoustic because the function does not seem to recognise the 'tag_type' argument:
> db_tags <- get_tags(con, tag_type = c("acoustic", "archival", "acoustic-archival"))
Error in get_tags(con, tag_type = c("acoustic", "archival", "acoustic-archival")) : 
  unused argument (tag_type = c("acoustic", "archival", "acoustic-archival"))

I am Rstudio server from VLIZ:
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.6 LTS

Not allowed to update the etn package either:
> install.packages('etn')
Installing package into ‘/data/home/innovauth/carlota.muniz@vliz.be/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘etn’ is not available (for R version 3.6.3)

Am I using deprecated parameters? Acoustic tags seem to show without issue.

**Comment by peterdesmet** [comment]
@cfmuniz I think you are indeed using an outdated version of the package (can be checked if you copy/paste the result of `sessionInfo()`) in this issue.

The package is not on CRAN, so `install.packages('etn')` won't work to update. Please use:

1. `devtools::install_github("inbo/etn")`
2. If asked to update dependencies, select all (this process can take a while).
3. The process will eventually fail for `odbc`, try `devtools::install_github("inbo/etn")` again and only select the remaining dependencies that are not `odbc`.
