### ISSUE TITLE
Code for finding owners of foreign (non-ghosts) tags on you receiver network

### ISSUE THREAD

**Issue by IPauwels** [inbo/etn#244]
**Is there a piece of code available already that can be used to go over a list of tags (full tag id) to check who these tags belong too?**

(_For now I specifically want to evaluate the attached list of tags. These full-tag-IDs were detected in the Rügen see, and the German researchers want to find out to whom the tags belong too._) 

@damianooldoni @peterdesmet @PieterjanVerhelst @jreubens
[unknown-animal (1).csv](https://github.com/inbo/etn/files/8729678/unknown-animal.1.csv)

**Comment by PieterjanVerhelst** [comment]
I don't think so. I think such a functionallity was discussed at the very beginning of this database and if I remember correctly, it was decided not to include this because you can often guess which species you detected based on the tag owner. This is in conflict with moratoria rules of course.

**Comment by jreubens** [comment]
Indeed, there is no code for that. This is something that is on the planning. However, once this is implemented, you won't be allowed to see the details, but only that there are detections.
To see the details you still will need to upload your metadata to the system (and than you automatically have access).

**Comment by peterdesmet** [comment]
Closing this issue, since it has been answered.
