### ISSUE TITLE
Some animal projects not appearing in the animal project list

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#246]
Reported by @jreubens and Carlota Muñiz:

I would need to have an overview of all detections of these animal projects:

```R
animals_thesis <- c("2010_phd_reubens", "2015_phd_verhelst_cod", "2015_phd_verhelst_eel",
  "2021_YEELAZ", "NARVAEEL", "PhD_Goossens", "Rijke_Noordzee", "codnoise",
  "FISHINTEL", "2012_leopoldkanaal", "2013_albertkanaal", "2014_demer",
  "2015_dijle", "2019_Grotenete", "2021_Dijle")
```
 And then I run

```R
detections_thesis <- get_acoustic_detections(
  animal_project_code = animals_thesis)
```
 
But it mentions “ Error: Invalid value(s) for animal_project_code argument.”
Any idea what the problem can be? I check all names and they all seem correct…

---

There is an issue with some animal projects not appearing in the animal project list. I did not have the issue with the previous ETN package version, but things started failing when I updated to the latest version.

See file attached. I think the project "2021_Dijle" I the one raising the issue.

I also had problems with all of this "VLIZ-MRC-AMUC-001", "VLIZ-MRC-AMUC-002", "cpod-lifewatch", "apelafico"

**Comment by peterdesmet** [comment]
@jreubens, as Carlota indicated, of the codes you used, `2021_Dijle` does not exist in the project table. `2021_Dijle_VPS` does, is that the one you are looking for?

- [x] `2010_phd_reubens`
- [x] `2015_phd_verhelst_cod`
- [x] `2015_phd_verhelst_eel`
- [x] `2021_YEELAZ` also code of a network project
- [x] `NARVAEEL` also code of a network project
- [x] `PhD_Goossens`
- [x] `Rijke_Noordzee`
- [x] `codnoise`
- [x] `FISHINTEL` also code of a network project
- [x] `2012_leopoldkanaal`
- [x] `2013_albertkanaal`
- [x] `2014_demer`
- [x] `2015_dijle`
- [x] `2019_Grotenete` also code of a network project
- [ ] `2021_Dijle`: does not exist, but `2021_Dijle_VPS` does, also as code of a network project

Regarding the following codes:

- [x] `VLIZ-MRC-AMUC-001` is a network project code
- [x] `VLIZ-MRC-AMUC-002` is a network project code
- [x] `cpod-lifewatch` is a network project code
- [x] `apelafico` is a network project code

**Comment by peterdesmet** [comment]
@jreubens please reopen this issue if that doesn't answer your question.

**Comment by PieterjanVerhelst** [comment]
Just a side note: the project `NARVAEEL` is not up to date. Some partners did not want the data to be uploaded in the ETN database.

**Comment by jreubens** [comment]
this answers the question.. thanks
