### ISSUE TITLE
Full project title available in ETN database

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#260]
In `common.projects` we have the information `name` (2014 Demer) and `code` (2014_demer). The information I'm looking for is the title (below) as provided in [IMIS](https://www.vliz.be/en/imis?module=dataset&dasid=5871).

@jreubens @aubrivliz Is that information also accessible through the ETN DB or do I need to query that from IMIS?

> 2014_DEMER - Acoustic telemetry data for four fish species in the Demer river (Belgium)

**Comment by aubrivliz** [comment]
@peterdesmet 
The project metadata is not provided in ETN, you need to query this from IMIS.

**Comment by peterdesmet** [comment]
Any advise on how to best do this? Is there an API?

**Comment by aubrivliz** [comment]
You can get the data in Json format. Example:

 [IMIS](https://www.vliz.be/en/imis?module=dataset&dasid=5871)
https://www.vliz.be/en/imis?module=dataset&dasid=5871&show=json

Just add the "&show=json"

**Comment by peterdesmet** [comment]
Excellent, thanks!
