### ISSUE TITLE
Map lifeStage to controlled vocab in DwC

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#262]
> For the standard vocabularies for lifestage, we at OTN hold a link to the NERC vocabulary: http://vocab.nerc.ac.uk/collection/S11/current/

_Originally posted by @diniangela in https://github.com/inbo/etn/issues/256#issuecomment-1332268387_

**Comment by peterdesmet** [comment]
Life stage values are currently not controlled and include

life_stage | cleaned value | vocab
--- | --- | ---
adult, Adult, ADULT | adult | http://vocab.nerc.ac.uk/collection/S11/current/S1116/
FII | ?
FIII | ?
FIV | ?
FV | ?
I | immature? | http://vocab.nerc.ac.uk/collection/S11/current/S1171/
imature | immature | http://vocab.nerc.ac.uk/collection/S11/current/S1171/
juvenile, JUVENILE | juvenile | http://vocab.nerc.ac.uk/collection/S11/current/S1127/
JUVENILE/ADULT | ? | not really http://vocab.nerc.ac.uk/collection/S11/current/S1145/ which is for groups
mature, Mature | adult? | http://vocab.nerc.ac.uk/collection/S11/current/S1116/
MII | ?
"NA", [empty] | [empty] | 
silver, Silver | adult?
smolt, SMOLT | uvenile or immature?
SUB-ADULT | sub-adult | http://vocab.nerc.ac.uk/collection/S11/current/S120/
unknown | **[empty]** | there is no unknown term in the S11 vocab

@PieterjanVerhelst can you help me map the values with ? to any of the terms in http://vocab.nerc.ac.uk/collection/S11/current/

**Comment by diniangela** [comment]
we use http://vocab.nerc.ac.uk/collection/S11/current/S1173/ for 'SMOLT'

**Comment by PieterjanVerhelst** [comment]
@peterdesmet 
Where the value is `JUVENILE/ADULT` that is a bit weird, since it can only be one of both. So it is rather inconclusive.
The values `I`, `FII`, `FIII`, `FIV`, `FV` and `MII` are eel classification stages according to Durif et al. (2005)[https://doi.org/10.1111/j.0022-1112.2005.00662.x](url)
For a cleaned value, we could do as follows:
`I`, `FII`, `FIII` = `juvenile`
`FIV`, `FV` and `MII` = `subadult`
`silver, Silver` = `subadult`

**Comment by peterdesmet** [comment]
Thanks @PieterjanVerhelst I have updated the table above. `yellow eel` and `silver eel` are unfortunately not available in http://vocab.nerc.ac.uk/collection/S11/current/S1173/ (@diniangela does it make sense if these were added?), so I currently mapped them your suggestions.

The remaining term to map is `mature`, which is not available in the vocab (immature) is. I guess I can safely map this to `adult`?

The `JUVENILE/ADULT` values are all from the SUPERSAT project. I won't map it, as it is indeed inconclusive and should be corrected.

**Comment by PieterjanVerhelst** [comment]
I would also suggest that `mature` is cleaned as `adult`.

**Comment by peterdesmet** [comment]
Thanks, now implemented

**Comment by timrobertson100** [comment]
Smolt is a new one to me.

Can you please let me know where we should place it in the vocabulary we align to at GBIF, and I'll see an issue is added?
https://registry.gbif.org/vocabulary/LifeStage/concepts 

We could either synonymise it to something there or create a new concept.
Thank you!

**Comment by peterdesmet** [comment]
@timrobertson100 note that there are likely many terms on the [BODC life stage vocabulary](http://vocab.nerc.ac.uk/collection/S11/current/) used by OBIS that aren't in the [GBIF registry](https://registry.gbif.org/vocabulary/LifeStage/concepts).

But for `smolt` specifically, I would add is as a synonym for `juvenile` (@PieterjanVerhelst or @diniangela can confirm this is a valid mapping)?

**Comment by timrobertson100** [comment]
Thanks @peterdesmet 
Mmmm... let's not focus just on one arbitrary term I spotted then. 
Perhaps it makes sense to go over the OBIS BODC and extend/align GBIFs with OBIS. LifeStage was something I did (as a non-biologist) simply by looking at what was published in GBIF to date - I then had the output reviewed before we imported it. It was always going to need refined.

Seem sensible?

**Comment by peterdesmet** [comment]
> Perhaps it makes sense to go over the OBIS BODC and extend/align GBIFs with OBIS.

Yes, that is a better approach.

**Comment by timrobertson100** [comment]
Thanks, @peterdesmet. We'll look in to that when we get a chance
