### ISSUE TITLE
with changes to helper functions, collapse_transformer() is no longer in use

### ISSUE THREAD

**Issue by PietrH** [inbo/etn#264]
In #257 (see also #256) the helper functions were revised: [zzz.R -> utils.R](https://github.com/inbo/etn/pull/257/files#diff-60bef5af43a1bd541299ce9bceeb226afb23deaa5e637b145c85e05ffd552b0c) including a change to check_value() where helper function collapse_transformer() was called. 

With the changes to check_value() in the pull request, collapse_transformer is no longer in use and can be removed.

**Comment by peterdesmet** [comment]
Yes `collapse_transformer` can be removed now that is no longer used (`glue_collapse()` is used instead).
