### ISSUE TITLE
Refactor input checks to common functionalities

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#27]
Cfr. the `check_null_or_value` input check, this should be extended to all functions having `network_project` or `animal_project` as input argument.

**Comment by peterdesmet** [comment]
This is now implemented for all parameters where it makes sense. First all valid values are queried with a `list_()` function and then compared with the input value using `check_value()`. See e.g.:

https://github.com/inbo/etn/blob/aa0b739f3866c3b83126fb275846cd921c724c6d/R/get_animals.R#L43-L50

The `animal_project_code_query` is the subquery (either TRUE or an actual subquery) that is then combined in a full SQL query:

https://github.com/inbo/etn/blob/aa0b739f3866c3b83126fb275846cd921c724c6d/R/get_animals.R#L62-L69
