### ISSUE TITLE
Add test to validate generated data package

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#275]
`download_acoustic_dataset()` creates 5 CSV files based on `get_` functions and adds a static [datapackage.json](https://github.com/inbo/etn/blob/main/inst/assets/datapackage.json) file, making it a Frictionless Data Package. Changes in the `get_` functions (e.g. adding a field, see #274) without updating `datapackage.json` would create invalid data packages.

It would therefore be good to have a test that verifies the output of `download_acoustic_dataset()` against its `datapackage.json`. That can be done using the frictionless R package, which can be added as a dev dependency.

The way I would do it is reading the datapackage and making sure no warnings occur when reading the resources.

```R
p <- frictionless::read_package("link/to/datapackage.json")
expect_no_warning(frictionless::read_resource(p, "animals"))
expect_no_warning(frictionless::read_resource(p, "tags"))
...
```

**Comment by PietrH** [comment]
What is a dev dependency? How do they differ from 'normal' ones?

**Comment by peterdesmet** [comment]
One that you list in `Suggests`, see explanation and useful usethis function at https://r-pkgs.org/description.html#sec-description-imports-suggests
