### ISSUE TITLE
Data for unit-tests

### ISSUE THREAD

**Issue by damianooldoni** [inbo/etn#28]
We are adding unit-tests to `etn` package. 
In particular we would like to test functions we are developing based on #9 . 
To do it, we need using data which are:
1. public available,
2. stable (= always present and never change)

Are there such data available?

**Comment by PieterjanVerhelst** [comment]
I think the data from project 2012_leopoldkanaal are suitable: finished project, so it doesn't change anymore and public available.

**Comment by jreubens** [comment]
another one is PhD Jan Reubens is another stable one.
Includes sync tags as well...

**Comment by damianooldoni** [comment]
Great! Thanks @PieterjanVerhelst , thanks @jreubens. I will go further writing the unit-tests in the afternoon.

**Comment by stijnvanhoey** [comment]
@bwydoogh any dummy or anonymous account to use for the unit-testing?

**Comment by stijnvanhoey** [comment]
@PieterjanVerhelst you provided two `animal` type projects, is there also an example to use of the `ǹetwork` type?

**Comment by damianooldoni** [comment]
@bwydoogh at the moment I am just asking username and psswd to users via old school way:

```r
readline(prompt = "Enter username: ")
``` 

Obviously, it would be better to have a dummy account for package tests; obviously with restricted access to data @PieterjanVerhelst  and @jreubens suggested. And a `network` project too as @stijnvanhoey noticed would be great!

**Comment by damianooldoni** [comment]
As @stijnvanhoey suggested, better to work with RStudio API:

```r
user <- rstudioapi::askForPassword("Username")
pwd <- rstudioapi::askForPassword("Password")
```

**Comment by stijnvanhoey** [comment]
@damianooldoni for the credentials discussion, see #33 
(actually, I just noticed that running the vignettes from command line with the `rstudioapi` does not work... :-()

**Comment by jreubens** [comment]
you can use 'Leopoldkanaal' and 'Thorntonbank' as network projects. Those are the two networks related to the animal projects suggested

**Comment by damianooldoni** [comment]
Thanks, @jreubens! You mean `thornton` and `leopold`, I think. There are 37 network projects up to now:
```r
valid_network_projects <- get_projects(connection = con,
                                       project_type = "network") %>%
  pull("projectcode")
```
