### ISSUE TITLE
Set absolute `url` to fix search

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#284]
To fix incorrect search result links (see https://github.com/inbo/camtraptor/issues/197) the following line:

https://github.com/inbo/etn/blob/35e70f3d284cb64494313e667f238378564d494b/_pkgdown.yml#L1

Should be updated to:

```yml
url: https://inbo.github.io/etn
```

This package however requires the pkgdown website to be build locally (rather than GitHub pages), so this is best done as part of an update to functions/documentation.

**Comment by PietrH** [comment]
Why does etn require the website to be built locally?
