### ISSUE TITLE
`write_dwc()` returns error: Expecting a single string value: [type=character; extent=0].

### ISSUE THREAD

**Issue by rubenpp7** [inbo/etn#293]
Hi,

I'm trying to run the following code but it gives me an error, could you take a look?
`data <- write_dwc(con, "2010_phd_reubens")`
Error
`Reading data and transforming to Darwin Core.
Error: Expecting a single string value: [type=character; extent=0].`

Thanks!

**Comment by rubenpp7** [comment]
Hi @peterdesmet 


yes, I made sure that I had the latest version but the issue persists

**Comment by PietrH** [comment]
I'm looking into this, I'll post updates in this issue.

**Comment by PietrH** [comment]
I suspect this actually broke when one of our dependencies `glue` got updated to v1.7.0: https://github.com/tidyverse/glue/releases/tag/v1.7.0 as part of https://github.com/tidyverse/glue/issues/272.

`rights_holder` is set to `NULL` by default, resulting in an empty sql query being returned by `glue::glue_sql()`, setting `rights_holder` to `"NULL"` results in valid sql being returned. 

I'm making headway.

**Comment by PietrH** [comment]
Fixed in branch, I'm opening a PR.

**Comment by PietrH** [comment]
@peterdesmet Could you review the PR?

**Comment by PietrH** [comment]
Hey Ruben,

It should be fixed now, just make sure you update to the latest version.

Thanks for making an issue!
