### ISSUE TITLE
`get_tags` to `get_transmitters`

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#30]
@jreubens and @PieterjanVerhelst, in #9, we defined the function `get_tags`. However, working on the code I do think it would be more consistent to call it `get_transmitters`, as this is the naming used in the detections view as well to define the tag identifiers. Moreover, it complements better the `get_receivers` function.

I propose to provide the function `get_transmitters` instead of `get_tags`, ok?

**Comment by jreubens** [comment]
definitely OK!
