### ISSUE TITLE
update vignettes to use API

### ISSUE THREAD

**Issue by PietrH** [inbo/etn#306]
The vignettes refer to `connect_to_etn()` which currently breaks them, they should also be updated to correctly document on how to use the API instead

- [ ] Mention `connect_to_etn()` deprecation
- [ ] Mention storing credentials for API
- [ ] Make sure they both work

----

- [x] acoustic telemetry

**Comment by PietrH** [comment]
Also partly implemented in #313

**Comment by PietrH** [comment]
Peter once mentioned to me that we are no longer maintaining the etn_fields vignette, while I see value in it, I believe making major changes to it to be out of scope of v2.3

**Comment by PietrH** [comment]
Works locally, I'm happy with it for v2.3 and to make improvements at a later refactoring stage.

**Comment by peterdesmet** [comment]
> Peter once mentioned to me that we are no longer maintaining the etn_fields vignette

I made that comment in error. It is referenced from dataset metadata in [IMIS](https://www.vliz.be/en/imis?dasid=5846&doiid=437):

<img width="562" alt="Screenshot 2024-09-30 at 15 27 09" src="https://github.com/user-attachments/assets/dc3eb726-d89b-4249-b8d2-55b2e7af158d">

> while I see value in it, I believe making major changes to it to be out of scope of v2.3

Agreed

**Comment by PietrH** [comment]
Alrighty, I've made an issue for a future update!
