### ISSUE TITLE
Create vignette about the handling of username/pwd

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#33]
We should inform the users to not store their credentials as such or support them properly so they don't have to... Some options are provided [here](http://db.rstudio.com/best-practices/managing-credentials/), but would be good to have a proper one documented to the users as part of the package: 

1. fixing this on the [server/DSN-level](http://db.rstudio.com/best-practices/managing-credentials/#integrated-security-with-dsn), would be nice (users just don't have to care): users are logged in, so would be good if it was automatically linke to their account, in order that `connect_to_etn()` would just work without credentials.... @bwydoogh any thought suggestions (or maybe this or a comparable option is actually supported)

2. If dbase level is not possible, how to handle this? [Different options](http://db.rstudio.com/best-practices/managing-credentials/) are described, any preferences? in short:, the options:

* config package using a simple `config` file in peoples user account?
* Environment variables that can be asked
* R general options with `options()`
* `rstudioapi::askForPassword("Database user"),`
* operating systems credential store with keyring package

**Comment by bwydoogh** [comment]
@stijnvanhoey 
>fixing this on the server/DSN-level, would be nice (users just don't have to care): users are logged in, so would be good if it was automatically linke to their account, in order that connect_to_etn() would just work without credentials.... @bwydoogh any thought suggestions (or maybe this or a comparable option is actually supported)

@stijnvanhoey I don't exactly know what you mean with a "_fix on the server-level_", as every user has a different credential. So I think you probably mean fixing this on the user his own machine (using Rstudio Desktop), by foreseeing this DSN. If you ask me, yes, this is the preferred solution (compared to requesting the user for this (username, password) combination).

**Comment by stijnvanhoey** [comment]
As currently the usage is only possible on the Rstudio server of VLIZ, I assumed that the user authentification of the Rstudio server application could be linked to some LDAP or AD based system that would support the user access to the databases as well. As such, the user would have access databases without having to authenticate again. Is that supported by Rstudio server?

**Comment by bwydoogh** [comment]
@stijnvanhoey Okay, now I understand it, sorry. We are aware of this problematic authentication step and will examine the use of LDAP. It is also requested within the context of another project here at VLIZ, so something that will be examined _(not sure whether we will have issues on Rstudio Server... no analysis has been made yet)_ and hopefully brought in place. But notice that this topic isn't something that will be realized in the short term (thus not available within the next couple of months).

**Comment by stijnvanhoey** [comment]
Thanks and good to know. As such, we have to inform users on the usage of their username/password and the issue remains open. 

In the current vignette, the usage of environmental variables is used and I actually like that approach as a temporary solution. Any reasons for choosing another option? @peterdesmet @damianooldoni

**Comment by damianooldoni** [comment]
@stijnvanhoey : no, no reason for not using it!
I am actually using it extensively in tests and I am saving other variables for usage in other repositories as well.

**Comment by stijnvanhoey** [comment]
Hence, we will promote the usage of environmental variables in a vignette, as explained [here](https://db.rstudio.com/best-practices/managing-credentials/#use-environment-variables)

**Comment by damianooldoni** [comment]
I find this documentation more than sufficient.
