### ISSUE TITLE
Release missing versions on GitHub

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#334]
The GitHub releases should preferably reflect all the available versions:

- [x] etn 1.0.0
- [x] etn 1.0.1
- [x] etn 2.0.0
- [x] etn 2.1.0
- [x] etn 2.2.0
- [x] etn 2.1.1
- [x] etn 2.2.0: https://github.com/inbo/etn/commit/57af8b24f4b6d107f36c16c3ed33f7859ac46077
- [x] etn 2.2.1: https://github.com/inbo/etn/commit/fa2528c9efc262e03b9669055bee0c5c43df696c
- [x] etn 2.3-beta
- [ ] etn 2.3.0: next official release

---

- The last released version should be `2.2.1`
- The current version number should be `2.2.1.9000`
- The next version should be `2.3.0`

**Comment by PietrH** [comment]
There is a release for 2.2.0, it has a different head than suggested: https://github.com/inbo/etn/releases/tag/v2.2.0
