### ISSUE TITLE
get_ functions output: tibble or just data.frame?

### ISSUE THREAD

**Issue by damianooldoni** [inbo/etn#36]
The output of the `get_` functions like `get_animals()` or `get_projects()` return a classic `data.frame`. However, nowadays more and more R developers tend to use `tibble` data.frames.
In order to see the differences among a tibble df and a normal df, read this [tutorial](https://tibble.tidyverse.org/) from `tidyverse` (yes, tibble comes from the `tidyverse` world!) or this chapter from [R for Data Science](http://r4ds.had.co.nz/tibbles.html).

**Comment by PieterjanVerhelst** [comment]
I would prefer a tibble data frame as well.

**Comment by jreubens** [comment]
From the tutorial it seems that tibble is better than a data.frame.
I'm not yet familiar with tibble, but I thrust you guys on this :-)
