### ISSUE TITLE
get_animals() suspect behavior if only network_project is given as input

### ISSUE THREAD

**Issue by damianooldoni** [inbo/etn#37]
I am wondering whether it is correct that 
```r
> animals <- get_animals(connection, network_project = "thornton")
> animals2 <- get_animals(connection, network_project = "leopold")
> animals3 <- get_animals(connection, network_project = c("leopold", "thornton"))
```
are equal. In fact no error is asserted by executing the code below:
```r
> testthat::expect_identical(animals, animals2)
> testthat::expect_identical(animals2, animals3)
```

Moreover, the `network_project` value given as input is not one of the `projectcode` in the output df:
```r
> which(animals %>% distinct(projectcode) %in% valid_network_projects)
integer(0)
> which(animals2 %>% distinct(projectcode) %in% valid_network_projects)
integer(0)
```
I would rather prefer an empty data.frame as output or a warning. Or maybe do I miss something about the structure of the database?

**Comment by stijnvanhoey** [comment]
Good comment!

@jreubens and @PieterjanVerhelst in #9 you defined as function for animals:
```
get_animals(
    netwerk_project,   # i.e. projectlist
    animal_project,   # i.e. tagprojectlist
    species)
```
but does it make sense to add the `network_project` argument here?

**Comment by PieterjanVerhelst** [comment]
I would say no, as the `animal_project` and `network_project` are linked with each other (e.g. animal project `2012_Leopoldkanaal` and network project `leopold`). When performing a selection based on the animal project, you get he animals of that project, which is what we want the function to do, no?
@jreubens what do you think?

**Comment by jreubens** [comment]
Network argument shouldn't be added. As you also want to see detections from your tags (i.e. animal project) on someone else's network...By default network projects should be 'all'...
Of course you should be able to select a specific network as well. (e.g  show me all detections that occurred in the Westernscheldt...)

**Comment by stijnvanhoey** [comment]
@jreubens if I understand you well:
- for the `get_animals` function, the usage of a network_project argument is useless and should be removed
- for the `get_detections` function, the usage of network_project and animal_project is required

ok?

**Comment by jreubens** [comment]
no.. network_project should be available to filter. It might be needed in some occasions to filter for specific network. But by default get_animals should include all network_projects

**Comment by PieterjanVerhelst** [comment]
Aah indeed, Jan is correct. When eels migrate to the North Sea, we detect them at various networks (Zeeschelde, Westerschelde, North Sea, Albert Canal...). For example, it occurs that we want to analyse the detections of the eels in the network of the Albert Canal only.

**Comment by stijnvanhoey** [comment]
As the default for all these arguments is to include all of them, I think we can close this issue here.
