### ISSUE TITLE
Parameters for get_transmitters()

### ISSUE THREAD

**Issue by jreubens** [inbo/etn#46]
- would be nice to have the filter function on species here as well
- filtering on sensor type, tag type, owner organisation would be nice as well
@PieterjanVerhelst other filters needed?

**Comment by PieterjanVerhelst** [comment]
- A filter on species would indeed be interesting. Just for the record: all transmitters in the database are linked with an animal or are unused transmitters also in the output of `get_transmitters()`?
-  Another interesting filter, would be on `end_date`. For example, to check which transmitters will die out at a specific moment.

**Comment by jreubens** [comment]
I think it shows everything in the database. If i run the command "my_tags <- get_transmitters(my_con)" I get 1904 records and there are currently 1801 animals in the db.
@bwydoogh would it be interesting to add a field 'transmitter_status' (similar as for receivers) to the tag metadata (with available, active and ended as options)?

**Comment by PieterjanVerhelst** [comment]
Yes, but it gives non-animal tags (e.g. built-in, sentinel...) as well.

**Comment by jreubens** [comment]
I checked the webapp. there are 2331 tags in the db
@bwydoogh can you provide a query with all unused tags in the db (i.e. available...)?

**Comment by bwydoogh** [comment]
> @bwydoogh can you provide a query with all unused tags in the db (i.e. available...)?

@jreubens You want a query or a list of? 
See https://bennyw.stackstorage.com/s/qOlafXLVonhB74f: the list of unused tags. 
If you want a query, please let me know.

**Comment by PieterjanVerhelst** [comment]
independently of an additional transmitter status, the suggested filters are redundant for the functionalities of the etn-package.

**Comment by jreubens** [comment]
agree with @PieterjanVerhelst

**Comment by stijnvanhoey** [comment]
If I understand the discussion, this issue handles the request of an additional field `transmitter_status` on the database level?

@bwydoogh remark that I use the following query for the ``get_transmitters` function:
```
      SELECT tags.*, animals.projectcode
      FROM vliz.tags
        LEFT JOIN vliz.animal_tag_release ON (animal_tag_release.tag_fk = tags.id_pk)
        LEFT JOIN vliz.animals_view animals ON (animals.id_pk = animal_tag_release.animal_fk)
      WHERE projectcode IN ({project*})
```
Either an adaptation of the tags-table is required or I should get the information on how to extend the query with the additional information to setup an `transmitter_status` column.

**Comment by bwydoogh** [comment]
@stijnvanhoey The `tags`-table will indeed by extended (one extra field), so this should be transparent.

**Comment by stijnvanhoey** [comment]
Thanks! Can you let us know on this issue when this is done, than we can test and close the issue.

**Comment by jreubens** [comment]
This has been performed, thus the test can be done.
