### ISSUE TITLE
connect_to_etn

### ISSUE THREAD

**Issue by JolienGoossens** [inbo/etn#48]
When using the function (both with the Sys.getenv and by typing my credentials in the function), I get:
Error: nanodbc/nanodbc.cpp:950: 28P01: [unixODBC]FATAL: password authentication failed for user "jolien.goossens@vliz.be" 

I double checked if I am using the right username and password (and tried with another account as well, same issue). Is this a problem of the code or should I change my access rights to ETN itself?

**Comment by bwydoogh** [comment]
@JolienGoossens I don't know which password you are using, but it is *not* the ETN data portal password. It is the password you got when requesting access to R-studio (_password is present in a `.pgpass` file_). So, which one did you use? Leave me an e-mail if you don't have that `.pgpass` file anymore.

**Comment by JolienGoossens** [comment]
Check!
