### ISSUE TITLE
transmitter type not standardised

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/etn#50]
When requesting the transmitter information, I see the following unique types:
```
      type
1 internal
2 acoustic
3 built-in
4 Acoustic
```
I would clear the usage of `acoustic` versus `Acoustic` on the database or import application side.

**Comment by stijnvanhoey** [comment]
intermezzo: we don(t do `rm(list = ls())` any more ;-)

**Comment by jreubens** [comment]
There is an inconsistency in the database.
We have 'tag_type' and 'acoustic_tag_type'
Tag_type should be 'Acoustic, DST, PIT, radio... and so on. thus meaning the type of telemetry.
within the tag_type 'Acoustic you should have the field 'Acoustic_tag_type'. with the different levels:
- animal
- built-in
- sync

We'll have to clean this up on database level first...
I'll discuss with @bwydoogh  how to proceed with this

**Comment by jreubens** [comment]
Perhaps it's better to change the field 'tag_type to 'telemetry_type' and 'acoustic_tag_type' to 'tag_type'.
Seems more logic to me...

**Comment by jreubens** [comment]
This adaptation has been done.
thus the field 'tag_type is changed to 'telemetry_type' and the field 'acoustic_tag_type' to 'tag_type'.
does there need to be done anything on code level here? or can this issue be closed

**Comment by bwydoogh** [comment]
@jreubens on code level? Don't think so, otherwise things wouldn't work anymore since May 2018.
So I guess you can close it.
