### ISSUE TITLE
Size limit data upload

### ISSUE THREAD

**Issue by PieterjanVerhelst** [inbo/etn#52]
I was trying to download the dataset of the animal network 2013_albertkanaal and apparently we cannot download files larger than 100 Mb. Is it possible to allow download of larger files?
Here is the error I got: Error: cannot allocate vector of size 100.0 Mb

**Comment by jreubens** [comment]
@bwydoogh something on our side?

**Comment by bwydoogh** [comment]
@jreubens I assume this happened on the R-studio server of VLIZ, so this is most likely infrastructure-related. In that case you will need to ask support (support@vliz.be).
