### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by PieterjanVerhelst** [inbo/etn#65]
When I recently downloaded data via the package, I noticed some coordinates were wrong or not filled in (i.e. 'NA'). Therefore, I think the retrieved coordinates were from the columns `Recover_lat` and `Recover_long`. However, the coordinates which should come with the data, are from the columns `Deploy_lat` and `Deploy_long`, which are a obliged field to fill in.

**Comment by stijnvanhoey** [comment]
As the `etn` package is using the database views as such without making selections of the columns concerning the coordinate information, i.e. the package just passes everything from dbase to user as such, I'm sending this to @bwydoogh and @jreubens as an issue on the database level.

@damianooldoni correct me if I'm wrong and we actually would do coordinate column name based filters.

**Comment by bwydoogh** [comment]
@stijnvanhoey Please some more information. The database view `detections_view` does return both the latitude / longitude on detection level and the latitude / longitude on deployment level. So what is missing here? Thanks 🙂.

**Comment by stijnvanhoey** [comment]
@PieterjanVerhelst can you provide to @bwydoogh  the commands you performed in order to retrieve the dataframe which should contain the coordinate information?

**Comment by PieterjanVerhelst** [comment]
This is the code I ran:
`nseel <- get_detections(my_con, network_project = "bpns" ,
                        scientific_name = "Anguilla anguilla")`

**Comment by PieterjanVerhelst** [comment]
Indeed, this is what you get. However, the columns `latitude` and `longitude` are the lats and longs from the ETN database fields `Recover_lat` and `Recover_long`, I think. Specifically, these are sometimes not filled in or erroneous. The columns `deployment_lat` and `deployment_long` are the obligatory fields from the ETN database: `deploy_lat` and `deploy_lon`.
I therefore suggest that the columns `latitude` and `longitude` are renamed as such: `recover_lat` and `recover_long`, so people who download the data know what lats and longs they can select for.

**Comment by PieterjanVerhelst** [comment]
Thanks for the clarification, now I understand :-). However, I think the `deploy_lat` and `deploy_lon` coordinates from the ETN database should come with the detections, because in the field, quick handling or hardware malfunction (e.g. gps) can lead to erroneous or absent coordinates filled in the receiver software and consequently the detections csv file.

**Comment by stijnvanhoey** [comment]
> I think the deploy_lat and deploy_lon coordinates from the ETN database should come with the detections

If I understand this correctly, these are already in the dataframe? What is the requested adaptation with respect to which table?

**Comment by PieterjanVerhelst** [comment]
Indeed, they are in the dataframe as `deployment_lat` and `deployment_long`. My request is to change the columns `latitude` and `longitude` in the dataframe into `recover_lat` and `recover_long`.

**Comment by stijnvanhoey** [comment]
This is a decision on the database level and should be agreed on by the user community. Should not interfere with the etn-package code. @bwydoogh  and @jreubens your decision

**Comment by bwydoogh** [comment]
@jreubens @PieterjanVerhelst I really don't know if we should change the field names. On deployment level we do have that `recover_lat` and `recover_long`, and can be freely modified by the scientist. The `latitude` and `longitude` on detection level cannot be changed and is the raw uploaded data. Same on database level: raw detection data is uploaded into the database, and `latitude` and `longitude` are 2 fields part of that raw detection data. Which is also the reason why they are called as such. I am not convinced.

**Comment by PieterjanVerhelst** [comment]
Than we need to come up with another solution, as the names are now very ambiguous: `latitude `and `longitude `are not specified what they are.

**Comment by bwydoogh** [comment]
@PieterjanVerhelst `detection_lat` and `detection_lon`? All the same to me, but no duplication of field names between different concepts (and which may even have different values as the actual `recover_lat` and `recover_lon` can be changed on deployment level). Other suggestions are also welcome.

**Comment by jreubens** [comment]
hmmm difficult one.
I suggest that 'latitude' and 'longitude' are not given standard  (set as FALSE?) when you do get_detections.
I agree with Benny to rename them to detection_lat and detection_long

**Comment by jreubens** [comment]
I just had a brief discussion with Benny and we decided the following:
- latitude and longitude from the csv files won't be used anymore, this raw data contains too many errors due to field deployments.
- Recover lat/long will be automatically duplicated from the deploy lat/long. And can be changed on DB level if needed.
- we rename lat/long to recover_lat and recover_long.
- this can stay like this in the dataframe from the get_detections call

clear for everyone?

**Comment by bwydoogh** [comment]
@jreubens OK.
One small additional note: it is not a rename of the field "lat" / "long" but the view `detections_view` (used by get_detections) will return the field `recover_lat` and `recover_lon` from the deployment.

**Comment by PieterjanVerhelst** [comment]
if I understand correctly, this `recover_lat` and `recover_lon` will be the same as the `deploy_lat` and `deploy_lon`? Just to be sure.
If this is the case, ok for me :-)

**Comment by jreubens** [comment]
They will indeed be the same, unless the mooring moved during deployment and you manually adapted it in the webapp
