### ISSUE TITLE
Error when loading package

### ISSUE THREAD

**Issue by jreubens** [inbo/etn#72]
When I want to load the package using
"devtools::install_github("inbo/etn")
library(etn)"
I get the following error
"Error: package ‘digest’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version"

I'm not sure what to do.
@damianooldoni or @peterdesmet can you help me out?

**Comment by damianooldoni** [comment]
It seems you need to reinstall digest package. 

You can try this:
1. Session tab -> "Restart R" (Ctrl + Shift + F10)
2. Digit `install.packages("digest")` in console
3. Try to install etn again by `devtools::install_github("inbo/etn")`

Let me know how it works.

**Comment by damianooldoni** [comment]
@jreubens: is the problem solved?

**Comment by jreubens** [comment]
yes it is!
Thanks for the help!

**Comment by PieterjanVerhelst** [comment]
I still have an error when trying to load the ETN R-package.
```{r}
> devtools::install_github("inbo/etn")
Error: package ‘processx’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```
Even after reinstalling package `processx` I get this error.

**Comment by damianooldoni** [comment]
Thanks @PieterjanVerhelst to let us know.
Is this a problem while using [RStudio server](http://rstudio.lifewatch.be/)? Or do you encounter this problem in your own R environment?

I have just connected to http://rstudio.lifewatch.be/ and I run `devtools::install_github("inbo/etn")`. 
I was asked whether I wanted to get some packages updated. I updated all them and everything works fine.

Could you please copy paste the session info? Type `devtools::session_info()` and copy paste the long output you get.

**Comment by PieterjanVerhelst** [comment]
Problem solved! I closed the R-session on the server and reopened it. Now I got also to question to upload some or all packages. After I did this, the etn-package was back on a role :-).
