### ISSUE TITLE
Incorrect time on machine running RStudio server

### ISSUE THREAD

**Issue by damianooldoni** [inbo/etn#73]
I was checking the package by launching the standard `devtools::check()` commando while I got this error which stops the check at an early stage:

```r
> checking for future file timestamps ... ERROR
  This system is set to the wrong time: please correct
     system: 2019-09-20 09:36 (UTC)
    correct: 2019-09-20 09:41 (UTC)
```

It seems that machine time is not correct? Could somebody with admin rights on the machine running Rstudio server check this asap? Thanks!

**Comment by bart-v** [comment]
Done

**Comment by damianooldoni** [comment]
Thanks. Problem is solved, indeed.
