### ISSUE TITLE
Required fields for publication of DwC occurrence data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#8]
For the publication of DwC occurrence data, the following fields are required at a detection view level:

## Already in detection_view

* [ ] `detections_view.id_pk`: is this a stable identifier for the detection that can be made public?
* [ ] `detections_view.datetime`
* [ ] `detections_view.transmitter` (= `tags.tag_code_space`)
* [ ] `detections_view.receiver` (= `receivers.receiver`)
* [ ] `detections_view.deployment_fk` (= `deployments_view.id_pk`)
* [ ] `detections_view.scientific_name` (= `animals_view.scientific_name`)
* [ ] `detections_view.deployment_station_name` (= `deployments_view.station_name`): contains the most stable names for locations
* [ ] `detections_view.animal_project_name` (= `projects_view.name`): assuming this is the field with stable names
* [ ] `detections_view.animal_moratorium` (= `projects_view.moratorium`)
* [ ] `detections_view.network_project_name` (= `projects_view.name`): assuming this is the field with stable names
* [ ] `detections_view.network_moratorium` (= `projects_view.moratorium`)

## Not yet available in detections_view

* [ ] `tags.owner_organization`
* [ ] `animals_view.id_pk`: decided we will use this as the stable ID for the animal
* [ ] `animals_view.common_name`
* [ ] `animals_view.animal_sex`
* [ ] `deployments_view.deploy_lat`: for fixed receivers and something else for wave-gliders
* [ ] `deployments_view.deploy_long`: for fixed receivers and something else for wave-gliders

**Comment by bwydoogh** [comment]
Done.

Added the following fields to the `detections_view` (matches with your demand, except for the **deployment latitude and longitude**: wave-gliders are not supported yet by the ETN DB. But once they are supported, the view will be modified as such) :

```
etn_group_tag.name AS tag_owner_organization,
animals.id_pk AS animal_id_pk,
animals.common_name AS animal_common_name,
animals.sex AS animal_sex,
deployments.deploy_lat AS deployment_lat,
deployments.deploy_long AS deployment_long
```
