### ISSUE TITLE
Update pkg to work with new views

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#80]
@jreubens @IPauwels @PieterjanVerhelst @fwaumans and myself completely reviewed the 5 views offered by ETN (tags, animals, receivers, deployments, detections) to make them consist and to expose users with the same information via the ETN application and the etn package.

Once @fwaumans is finished with implementing the views, we should update all functions to make use of the new views. This might imply renaming some parameters.

**Comment by damianooldoni** [comment]
Thansk @peterdesmet to let me know. That's a great news!
@fwaumans: do you have an idea about time schedule? Just to reserve some days in my agenda.

**Comment by peterdesmet** [comment]
This has now been done in #93
