### ISSUE TITLE
Cannot edit .Renviron on rstudio.lifewatch.be

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#81]
@fwaumans, I notice my `.Renviron` file on rstudio.lifewatch.be contains:

```
username="..."
password="..."

```

I would like to update this to:

```
userid="..."
pwd="..."
```

Which is the RStudio default (https://db.rstudio.com/best-practices/managing-credentials/#use-environment-variables) and used by this vignette:

https://github.com/inbo/etn/blob/03d60109a8315fd5d76c41db35d674b29c1b7cc0/vignettes/access-etn-data.Rmd#L40-L41

When I try to do so, I get:

> this source file is read-only so changes cannot be saved

Can this be resolved?

**Comment by bart-v** [comment]
Fixed
`chown peterd:lifewatch .Renviron`
