### ISSUE TITLE
Don't export certain functions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#82]
I noticed that for some helper functions/variables, pages are build on pkgdown where they probably should just stay internal:

- [x] https://inbo.github.io/etn/reference/ETN_SERVER.html
- [x] https://inbo.github.io/etn/reference/check_connection.html
- [x] https://inbo.github.io/etn/reference/check_datetime.html
- [x] https://inbo.github.io/etn/reference/check_null_or_value.html
- [x] https://inbo.github.io/etn/reference/collapse_transformer.html
- [x] https://inbo.github.io/etn/reference/deployment_station_names.html
- [x] https://inbo.github.io/etn/reference/scientific_names.html

@damianooldoni they probably need some Roxygen remark?

**Comment by damianooldoni** [comment]
Well, these functions are not listed in the [Reference](https://inbo.github.io/etn/reference/index.html) as we don't export them via `@export` in Roxygen. So, users don't get so easily to these helper functions unless they type the URL you mentioned, something I have never done, actually :smile: 

By the way, i will add `@keywords internal` to solve this issue.

**Comment by damianooldoni** [comment]
Bby the way, it seems `@keywords internal` doesn't work anymore with Roxygen 6.1.1 or higher.

**Comment by damianooldoni** [comment]
I have to remove the Rds from `man` first, of course...

**Comment by peterdesmet** [comment]
Fixed
