### ISSUE TITLE
How to select acoustic vs c-pod?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#85]
1. Are those two separate types of data that should never be shown together: e.g. never showing receivers for both c-pod and acoustic at the same time?
2. Should the visible fields in receivers, deployments and detections differ between acoustic and c-pod, or should it be the same, i.e. different views or shared views?
3. Dependent on 2 we need a way to select c-pod vs acoustic. For now we can only make that selection in the (shared) view of receivers.

**Comment by PieterjanVerhelst** [comment]
@peterdesmet the c-pod and acoustic telemetry data are two complete different systems, working on complete different animals. So in my opinion we should treat them as such and do not show them together.
With your second question, do you mean the view of the interface? Both can have the same interface style, but should be kept separate.

**Comment by peterdesmet** [comment]
By `view`, I mean what is returned by the database. For now, the receiver `view` returns both acoustic and c-pod.

**Comment by PieterjanVerhelst** [comment]
I would suggest to keep both techniques separate, since a c-pod is a completely different thing than an acoustic receiver.

**Comment by jreubens** [comment]
1. it are two different systems.However, the cpods are moored with an VR2AR receiver, which detects fish as well. Thus I would include them.
2. There are differences in the available/interesting fields for deployment, receiver and detections for cpod and acoustic. 
3. THus the selection criterion is needed

**Comment by peterdesmet** [comment]
Ok, will add selection criterion. Note to self: test if `1610-POD` appears in other views.

**Comment by peterdesmet** [comment]
@fwaumans can you add the field `application_type` to:

- [ ] `projects_view2`: rename `context_type`, see #102 
- [x] `receivers_view2`: already the case, as 3rd field (between `receiver_id` and `telemetry_type`)
- [ ] `deployments_view2`: field `application_type` as 3rd field (between `receiver_id` and `network_project_code`)
- [ ] `detections_view2`: field `application_type` as 4th field (between `receiver_id` and `network_project_code`)

**Comment by peterdesmet** [comment]
For now, I would reuse the same views for both application types (=> same fields for both application types), but add a field so one can filter between one and the other: #103.
