### ISSUE TITLE
Create projects view

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#86]
Create a view for projects, with specific names and order of fields.

View is defined in the spreadsheet: https://docs.google.com/spreadsheets/d/1XVmoxrzxoBGqC7AYBjTgzUAer0w04D6iiCJW2TW41SU/edit?usp=sharing

**Comment by fwaumans** [comment]
Project view was created: project_view2

**Comment by peterdesmet** [comment]
Great! I will update the package to use it

**Comment by peterdesmet** [comment]
Fixed in f16a71e
