### ISSUE TITLE
How to return animal-tag relationship?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#88]
Currently:

- `get_tags()` doesn't return unique tags, as it's internally linked to animals to allow filtering on animal project. Since a tag (`A69-1303-20695`) can be associated with multiple animals (`673` and `674`), duplicates are returned
- `get_animals()` doesn't return unique animals, as the view return animals + their tag ID. Since an animal (`2369`) can be associated with multiple tags (`A69-9006-971` and `A69-9006-972`) duplicates are returned.

I would:

- `get_tags()`: remove the option to select on animal project, so the function (just like the view and the table on the website) returns **unique tags**
- `get_animals()`: return **unique animals** by default, which is similar to how the website displays a single row per animal:

<img width="856" alt="Screenshot 2020-02-19 at 16 25 34" src="https://user-images.githubusercontent.com/600993/74852124-78ea8500-533c-11ea-8bda-94651cb1a510.png">

- `get_animals()`: add an option to include `tag_fk` (resulting in multiple), so one can join with information from `get_tags()`

**Comment by damianooldoni** [comment]
After discussing `get_animals()` with @peterdesmet, we opt for the following option:  return **unique animals** collapsing tags in a comma separated string.

**Comment by damianooldoni** [comment]
There are multiple tag related columns in returned data.frame of `get_animals()`:
1. `tag_id`
2. `tag_fk`
3. `tagger`
4. `tagging_type`
5. `tagging_methodology`

Example:
| pk | tag_id | tag_fk | tagger | tagging_type | tagging_methodology
| --- | --- | --- | --- | --- | --- |
2827 | A69-9006-904 | 1794 | - | Internal | 
2827 | A69-9006-903 | 1793 | - | Internal | 

A possible strategy is to collapse not only `tag_id` but all `tag*` columns to comma separated values. Example:

| pk | tag_id | tag_fk | tagger | tagging_type | tagging_methodology
| --- | --- | --- | --- | --- | --- |
2827 | A69-9006-904,A69-9006-903 | 1794, 1793 | -,- | Internal,Internal | 

@peterdesmet, what do you think?

**Comment by peterdesmet** [comment]
Agree: all tag* columns

**Comment by damianooldoni** [comment]
PR #106 should solve uniqueness of `get_animals`(). 
About `get_tags()`, it seems that it is already fixed.

**Comment by peterdesmet** [comment]
Fixed in #106
