### ISSUE TITLE
Many receivers don't have network_project_code in new view

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#89]
`get_receivers()` will in the background look for all network codes and filter receivers on those with a network code. As a result, that currently only returns 12 entries.

```R
receivers_all <- DBI::dbGetQuery(connection, "SELECT * FROM vliz.receivers_view2")
```

Returns 1640 entries, many of them without `network_project_code`. Why is this information missing?

**Comment by peterdesmet** [comment]
Ping @fwaumans

**Comment by fwaumans** [comment]
The network_project_code is based on the field` financing_project_fk` in the `receiver` table. In most of the records, this field is empty.

**Comment by peterdesmet** [comment]
Aha, in that case I will have to update some functions.

We should probably rename the field to `financing_project` (cf. `tags`) and move it lower. I'll get back to you on this.

**Comment by peterdesmet** [comment]
Indeed, and the field `financing_project` is already part of that view, with the same information. @fwaumans you can remove `network_project_code` from `receivers_view2`.

**Comment by fwaumans** [comment]
The field `financing_project ` was removed.

**Comment by peterdesmet** [comment]
You meant `network_project_code` was removed. 👍
