### ISSUE TITLE
External database access: considerations and discussion

### ISSUE THREAD

**Issue by niconoe** [inbo/etn#91]
I've recently had a conversation with my colleague @peterdesmet  about the possibility, for the European Tracking Network, to give access to a PostgreSQL database (hosted at VLIZ) over the Internet.

A few details about how we would like to implement this:

A small group of users will have access to this database in read-only mode. We also plan to make use of the row security policies feature of PostgreSQL so each user has only access to the rows that concern him/her. Since we don’t have much experience with this feature and its limitations, we plan to implement a small prototype to make sure the correct access restrictions can be easily implemented.

**About exposing PostgreSQL over the Internet:**

I agree this route opens one more “door” to the network infrastructure than a more traditional approach (such as a data visualization web app that loads its data from a database that’s, in itself, accessible from the outside network), but we think it would work well for this project well and the risks can be greatly mitigated:

- Direct database access would give great flexibility (manual SQL queries) at a very limited cost for this small group of experienced users.
- The access would be read-only, with only access to a subset of rows.
- If you prefer to have this database separated from your other PostgreSQL databases, we could run it in a separated/more isolated environment (such as a dedicated machine on the DMZ)
- We’d pay attention to the usual security measures: always keep PostgreSQL updated (in case of security issues in the PostgreSQL server itself), use SSL, strong passwords, … We can also automate (script, tests, …) the data updates, so the user permissions are automatically configured, and checked periodically.

Maybe we could also reduce the surface attack further by forcing that traffic through a tunnel such as OpenVPN. That would require more configuration on both sides ( infrastructure + users), so we’d need to assess the feasibility first.

Don’t hesitate to give us feedback over this. In short: we’d like to take this route but understand the concerns and would like to work together to reach a good solution for everyone involved.

**Comment by peterdesmet** [comment]
Ping @fwaumans: some ideas/suggestions on how internet access to ETN database could be provided.

**Comment by bart-v** [comment]
As explained during our "R meeting", we will not expose PostgreSQL to the internet.
We are in the process of a developing an API, that can do all of this, based on OpenCPU, see https://www.opencpu.org

**Comment by peterdesmet** [comment]
Will the API have login capabilities, so ETN users can access their non-public data?

**Comment by bart-v** [comment]
Yes
