### ISSUE TITLE
API design: alias singular and plural functions

### ISSUE THREAD

**Issue by niconoe** [inbo/etn#92]
Following discussions with @peterdesmet: 

I personally quite like when the name of a functions gives a good idea about what it returns. That applies too to singular/plural: I expect to find:

- `get_receiver(receiver_id=x)`, that returns a single receiver. But also:
- `get_receivers(project_id=y)` that returns a multiple receivers.

I was therefore wondering if we could/should alias functions so `get_receiver`=`get_receivers`.

**Comment by peterdesmet** [comment]
@jreubens @PieterjanVerhelst @IPauwels do you see a need for this: having both single `get_project()` and plural `get_projects()` function names? All names are currently plural: https://inbo.github.io/etn/reference/index.html

**Comment by peterdesmet** [comment]
Method to implement this: https://github.com/tidyverse/dplyr/blob/abb86fc49cbfda0d036a871c76b6bdd10030fc63/R/summarise.R#L107-L109

**Comment by PieterjanVerhelst** [comment]
I personally don't think that is necessary and would keep one function.

**Comment by IPauwels** [comment]
> I personally don't think that is necessary and would keep one function.

same here..

**Comment by peterdesmet** [comment]
Ok, closing without further action. Thanks for the suggestion @niconoe: now I at least know how to do it.
