### ISSUE TITLE
Decide on application_type vs context_type

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn#96]
The field for `acoustic_telemetry` vs `cpod` is named differently:

- In projects: `context_type`
- In receivers: `application_type`

I find `context_type` a better name. Should we use that for all?

**Comment by PieterjanVerhelst** [comment]
I would prefer `application_type`.

**Comment by peterdesmet** [comment]
@jreubens @IPauwels?

**Comment by peterdesmet** [comment]
Ok, will create issue to make some changes in DB.

**Comment by jreubens** [comment]
agreed!
